import hashlib
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List, Tuple

from ..naming import _avoid_keyword, class_name_for
from .ir import BlockIR, CxfIR, PortIR
from .parser import ROOT_PREFIX

_ACRONYM_BOUNDARY = re.compile(r'(?<=[a-z0-9])(?=[A-Z])|(?<=[A-Z])(?=[A-Z][a-z])')


def _module_segment(name: str) -> str:
    """Acronym-aware camel/underscore -> snake_case for CXF package/module
    names ('AHUs' -> 'ah_us', 'VAV' -> 'vav'). ingest/naming.py's snake_case()
    splits on every capital letter, which mangles the many acronym-heavy CXF
    path segments (VAV, AHUs, ASHRAE...) into unreadable output - not used for
    field/relation names anywhere else, so kept local to this emitter rather
    than changed there."""
    s = name.replace('-', '_')
    s = _ACRONYM_BOUNDARY.sub('_', s)
    s = re.sub(r'_+', '_', s)
    return _avoid_keyword(s.lower())


HEADER = '''"""AUTO-GENERATED by semantic_objects.ingest - DO NOT EDIT.

Source ontology: {source_dir}
Source file count SHA256: {source_hash}

Regenerate with: python -m semantic_objects.ingest.cli --ontology cxf
Hand customizations belong in the sibling non-generated module, which imports
from this one - never edit this file directly, changes will be overwritten.
"""
'''


def _source_hash(source_dir: Path) -> str:
    h = hashlib.sha256()
    for path in sorted(source_dir.rglob('*.jsonld')):
        h.update(path.read_bytes())
    return h.hexdigest()


def _module_path(dotted_path: str) -> Tuple[List[str], str]:
    """dotted_path -> (package segments, leaf module name), all snake_cased."""
    segments = dotted_path.split('.')
    return [_module_segment(s) for s in segments[:-1]], _module_segment(segments[-1])


def _qualified_module(dotted_path: str) -> str:
    pkg, leaf = _module_path(dotted_path)
    return '.'.join(['semantic_objects', 'cxf', '_generated', 'blocks'] + pkg + [leaf])


def _pascal(segment: str) -> str:
    return ''.join(part.capitalize() for part in segment.split('_') if part)


def _disambiguating_aliases(items: Dict[str, str]) -> Dict[str, str]:
    """items: dotted_path -> class_name: several different sibling folders can
    produce the same leaf class name (e.g. VentilationZones/ASHRAE62_1/
    Setpoints.jsonld and .../Title24/Setpoints.jsonld both generate a class
    named `Setpoints`; two different Subsequences/Alarms.jsonld files under
    CoolingOnly vs Reheat both generate `Alarms`). Importing colliding names
    into the same namespace (a flat re-export module, or a block module that
    composes two of them as sibling sub-blocks) would silently shadow one with
    the other - returns dotted_path -> alias, using just enough trailing
    package segments to make every colliding name distinct again (all
    occurrences get a qualified alias, not just the second one, so it's never
    ambiguous which import is "the real name")."""
    by_class_name: Dict[str, List[str]] = {}
    for dotted, class_name in items.items():
        by_class_name.setdefault(class_name, []).append(dotted)

    aliases: Dict[str, str] = {}
    for class_name, dotted_list in by_class_name.items():
        if len(dotted_list) == 1:
            aliases[dotted_list[0]] = class_name
            continue
        pkg_lists = {dt: _module_path(dt)[0] for dt in dotted_list}
        max_depth = max((len(segs) for segs in pkg_lists.values()), default=1) or 1
        for depth in range(1, max_depth + 1):
            candidate = {
                dt: ''.join(_pascal(s) for s in (segs[-depth:] if depth <= len(segs) else segs)) + class_name
                for dt, segs in pkg_lists.items()
            }
            if len(set(candidate.values())) == len(dotted_list):
                aliases.update(candidate)
                break
        else:
            aliases.update({dt: class_name_for(dt.replace('.', '_')) for dt in dotted_list})
    return aliases


class CxfEmitter:
    """Emits a CxfIR into generated Python modules: one flat enumerationkinds
    module (10 CXF Types - small enough that a flat file beats mirroring the
    folder hierarchy, unlike blocks below), and one package tree under
    blocks/ that mirrors the CXF folder hierarchy 1:1 (37 blocks, several of
    which share a leaf name across sibling folders - e.g. two different
    Subsequences/Alarms.jsonld - so package nesting is what keeps *module*
    paths collision-free; class names that still collide once re-exported
    into a single namespace - the flat blocks/__init__.py, or two sub-blocks
    composed by the same parent, or two enum types sharing a literal name -
    get a qualified alias, see _disambiguating_aliases).
    """

    def __init__(self, ir: CxfIR, source_dir: Path, output_dir: Path):
        self.ir = ir
        self.source_dir = Path(source_dir)
        self.output_dir = Path(output_dir)
        self.source_hash = _source_hash(self.source_dir)
        self._literal_aliases: Dict[Tuple[str, str], str] = {}  # populated by _emit_enumerationkinds

    def emit(self) -> None:
        self._emit_enumerationkinds()
        self._emit_blocks()
        self._emit_meta()

    def _emit_meta(self) -> None:
        lines = [
            HEADER.format(source_dir=self.source_dir, source_hash=self.source_hash),
            '',
            f'SOURCE_DIR = {str(self.source_dir)!r}',
            '',
            f'SOURCE_SHA256 = {self.source_hash!r}',
            '',
            f'GENERATED_AT = {datetime.now(timezone.utc).isoformat()!r}',
            '',
            f'BLOCK_COUNT = {len(self.ir.blocks)}',
            '',
            f'ENUMERATION_KIND_COUNT = {len(self.ir.enum_types)}',
            '',
            f'QUANTITYKINDS_REFERENCED = {sorted(self.ir.quantitykinds_referenced)!r}',
            '',
            f'UNITS_REFERENCED = {sorted(self.ir.units_referenced)!r}',
        ]
        (self.output_dir / '_meta.py').write_text('\n'.join(lines) + '\n')

    # --- enumerationkinds.py -------------------------------------------------

    def _literal_class_name(self, enum_dotted: str, lit_name: str) -> str:
        """The class name a given enum type's literal was actually emitted
        under - see the collision handling in _emit_enumerationkinds. Used both
        there and by _render_parameter_field, which needs to reference the
        exact same (possibly qualified) name for a parameter's default value.
        Falls back to the unqualified name if the pair was never registered
        (a parameter default naming a literal its enum type doesn't actually
        declare - shouldn't happen in this corpus, but shouldn't crash codegen
        either)."""
        return self._literal_aliases.get((enum_dotted, lit_name), class_name_for(lit_name))

    def _emit_enumerationkinds(self) -> None:
        # Different CXF enum types can share a literal name (e.g. both
        # ASHRAEClimateZone and Title24ClimateZone have a 'Not_Specified'
        # literal) - defining both classes under the same bare name in this one
        # flat module would silently let the second definition replace the
        # first. Resolve a collision-free name per (enum type, literal) pair
        # up front, the same way block/sub-block class names are resolved, and
        # keep the map around so parameter defaults (rendered later, in
        # _render_parameter_field) reference the same name.
        proposed: Dict[str, List[Tuple[str, str]]] = {}  # class_name -> [(enum_dotted, lit_name), ...]
        for dotted, et in self.ir.enum_types.items():
            seen_in_type: set = set()
            for lit_name, _ in et.literals:
                if lit_name in seen_in_type:
                    continue  # duplicate literal within the same enum type - keep first
                seen_in_type.add(lit_name)
                proposed.setdefault(class_name_for(lit_name), []).append((dotted, lit_name))

        self._literal_aliases = {}
        for lit_class, occurrences in proposed.items():
            if len(occurrences) == 1:
                dotted, lit_name = occurrences[0]
                self._literal_aliases[(dotted, lit_name)] = lit_class
            else:
                for dotted, lit_name in occurrences:
                    et = self.ir.enum_types[dotted]
                    self._literal_aliases[(dotted, lit_name)] = f'{et.class_name}_{lit_class}'

        lines = [HEADER.format(source_dir=self.source_dir, source_hash=self.source_hash)]
        lines.append('from ..core import EnumerationKind')
        lines.append('from ...core import semantic_object')
        lines.append('')
        all_names = []
        for dotted, et in sorted(self.ir.enum_types.items()):
            all_names.append(et.class_name)
            lines.append('')
            lines.append('@semantic_object')
            lines.append(f'class {et.class_name}(EnumerationKind):')
            lines.append(f'    _name = {(ROOT_PREFIX + dotted)!r}')
            if et.description:
                lines.append(f'    comment = {et.description!r}')
            lines.append('')
            seen_in_type: set = set()
            for lit_name, lit_desc in et.literals:
                if lit_name in seen_in_type:
                    continue
                seen_in_type.add(lit_name)
                lit_class = self._literal_class_name(dotted, lit_name)
                all_names.append(lit_class)
                lines.append('')
                lines.append(f'@semantic_object')
                lines.append(f'class {lit_class}({et.class_name}):')
                lines.append(f'    _name = {lit_name!r}')
                if lit_desc:
                    lines.append(f'    comment = {lit_desc!r}')
        lines.insert(3, f'__all__ = {all_names!r}')
        path = self.output_dir / 'enumerationkinds.py'
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text('\n'.join(lines) + '\n')

    # --- blocks/** ------------------------------------------------------------

    def _emit_blocks(self) -> None:
        blocks_dir = self.output_dir / 'blocks'
        blocks_dir.mkdir(parents=True, exist_ok=True)
        package_dirs = {blocks_dir}

        for dotted, block in sorted(self.ir.blocks.items()):
            pkg_segments, leaf = _module_path(dotted)
            module_dir = blocks_dir.joinpath(*pkg_segments)
            module_dir.mkdir(parents=True, exist_ok=True)
            for i in range(len(pkg_segments) + 1):
                package_dirs.add(blocks_dir.joinpath(*pkg_segments[:i]))
            module_path = module_dir / f'{leaf}.py'
            module_path.write_text(self._render_block_module(block))

        for d in package_dirs:
            init = d / '__init__.py'
            if not init.exists():
                init.write_text('')

        # Flat re-export surface: `from semantic_objects.cxf._generated.blocks import Controller`.
        # Several distinct blocks share a leaf class name across sibling folders
        # (three different `Controller`s, two different `Alarms`) - importing
        # all of them under their bare name here would silently shadow one with
        # another, so aliasing follows the same rule as _sub_block_aliases.
        class_names = {dotted: block.class_name for dotted, block in self.ir.blocks.items()}
        aliases = _disambiguating_aliases(class_names)

        lines = [HEADER.format(source_dir=self.source_dir, source_hash=self.source_hash)]
        for dotted, block in sorted(self.ir.blocks.items()):
            pkg_segments, leaf = _module_path(dotted)
            mod_suffix = '.'.join(pkg_segments + [leaf])
            alias = aliases[dotted]
            if alias == block.class_name:
                lines.append(f'from .{mod_suffix} import {block.class_name}')
            else:
                lines.append(f'from .{mod_suffix} import {block.class_name} as {alias}')
        lines.append('')
        lines.append(f'__all__ = {sorted(aliases.values())!r}')
        (blocks_dir / '__init__.py').write_text('\n'.join(lines) + '\n')

    def _render_block_module(self, block: BlockIR) -> str:
        imports = {
            'from semantic_objects.cxf.core import Block',
            'from semantic_objects.core import semantic_object',
        }
        field_helpers_used = set()
        field_lines: List[str] = []

        for port in block.inputs:
            field_helpers_used.add(self._io_helper_name(port, 'input'))
            field_lines.append(self._render_io_field(port, 'input', imports))
        for port in block.outputs:
            field_helpers_used.add(self._io_helper_name(port, 'output'))
            field_lines.append(self._render_io_field(port, 'output', imports))
        for port in block.parameters:
            helper, rendered = self._render_parameter_field(port, imports)
            field_helpers_used.add(helper)
            field_lines.append(rendered)

        sub_aliases = self._sub_block_aliases(block)
        for sub in block.sub_blocks:
            field_helpers_used.add('subblock_field')
            field_lines.append(self._render_subblock_field(sub, sub_aliases, imports))

        if field_helpers_used:
            imports.add(f"from semantic_objects.cxf.fields import {', '.join(sorted(field_helpers_used))}")

        lines = [HEADER.format(source_dir=self.source_dir, source_hash=self.source_hash)]
        lines.extend(sorted(imports))
        lines.append('')
        lines.append(f"__all__ = {[block.class_name]!r}")
        lines.append('')
        lines.append('')
        lines.append('@semantic_object')
        lines.append(f'class {block.class_name}(Block):')
        lines.append(f'    _name = {(ROOT_PREFIX + block.dotted_path)!r}')
        if block.description:
            lines.append(f'    comment = {block.description!r}')
        if not field_lines:
            lines.append('    pass')
        else:
            lines.extend(f'    {fl}' for fl in field_lines)
        return '\n'.join(lines) + '\n'

    @staticmethod
    def _io_helper_name(port: PortIR, direction: str) -> str:
        return f'{port.value_type.lower()}_{direction}_field'

    def _render_io_field(self, port: PortIR, direction: str, imports: set) -> str:
        helper = self._io_helper_name(port, direction)
        py_type = {'Real': 'RealInputPort' if direction == 'input' else 'RealOutputPort',
                   'Boolean': 'BooleanInputPort' if direction == 'input' else 'BooleanOutputPort',
                   'Integer': 'IntegerInputPort' if direction == 'input' else 'IntegerOutputPort'}[port.value_type]
        imports.add(f'from semantic_objects.cxf.core import {py_type}')
        kwargs = [f'description={port.description!r}']
        if port.value_type == 'Real':
            if port.quantitykind_local:
                imports.add('from semantic_objects.qudt import quantitykinds')
                kwargs.insert(0, f'qk=quantitykinds.{port.quantitykind_local}')
            if port.unit_local:
                imports.add('from semantic_objects.qudt import units')
                kwargs.insert(1 if port.quantitykind_local else 0, f'unit=units.{_unit_attr(port.unit_local)}')
        return f'{port.name}: {py_type} = {helper}({", ".join(kwargs)})'

    def _render_parameter_field(self, port: PortIR, imports: set) -> Tuple[str, str]:
        if port.value_type == 'Real':
            helper, py_type = 'real_parameter_field', 'RealParameter'
            kwargs = [f'default={port.default_value!r}']
            if port.quantitykind_local:
                imports.add('from semantic_objects.qudt import quantitykinds')
                kwargs.append(f'qk=quantitykinds.{port.quantitykind_local}')
            if port.unit_local:
                imports.add('from semantic_objects.qudt import units')
                kwargs.append(f'unit=units.{_unit_attr(port.unit_local)}')
            kwargs.append(f'description={port.description!r}')
        elif port.value_type == 'Boolean':
            helper, py_type = 'boolean_parameter_field', 'BooleanParameter'
            kwargs = [f'default={port.default_value!r}', f'description={port.description!r}']
        elif port.value_type == 'Integer':
            helper, py_type = 'integer_parameter_field', 'IntegerParameter'
            kwargs = [f'default={port.default_value!r}', f'description={port.description!r}']
        elif port.value_type in self.ir.enum_types:
            helper, py_type = 'enum_parameter_field', 'EnumParameter'
            enum_type = self.ir.enum_types[port.value_type]
            imports.add('from semantic_objects.cxf._generated import enumerationkinds')
            kwargs = [f'enumeration_kind=enumerationkinds.{enum_type.class_name}']
            if port.default_value:
                lit_class = self._literal_class_name(port.value_type, str(port.default_value))
                kwargs.append(f'default=enumerationkinds.{lit_class}')
            kwargs.append(f'description={port.description!r}')
        else:
            helper, py_type = 'unknown_parameter_field', 'Parameter'
            kwargs = [f'default={port.default_value!r}', f'description={port.description!r}']

        imports.add(f'from semantic_objects.cxf.core import {py_type}')
        return helper, f'{port.name}: {py_type} = {helper}({", ".join(kwargs)})'

    def _sub_block_aliases(self, block: BlockIR) -> Dict[str, str]:
        """Map this block's own sub_blocks' block_type_dotted -> the name to
        import that sub-block's class as in this module (see
        _disambiguating_aliases)."""
        items = {}
        for sub in block.sub_blocks:
            target = self.ir.blocks.get(sub.block_type_dotted)
            if target is not None:
                items[sub.block_type_dotted] = target.class_name
        return _disambiguating_aliases(items)

    def _render_subblock_field(self, sub, sub_aliases: Dict[str, str], imports: set) -> str:
        # Annotated as SubBlock, not as the referenced block type: the runtime
        # default is a SubBlock(block_type=..., description=...) wrapper, not
        # an instance of the sub-block itself (no wiring/values to construct
        # one with) - annotating the field as the sub-block's own type would
        # make Resource.__post_init__'s auto-coercion (core.py) try to build one
        # by calling BlockType(<the SubBlock wrapper>) positionally, silently
        # corrupting the field instead of leaving the wrapper alone.
        imports.add('from semantic_objects.cxf.core import SubBlock')
        target = self.ir.blocks.get(sub.block_type_dotted)
        if target is None:
            # A sub-block instance whose type isn't in the ~45-file CXF corpus we
            # ingest (e.g. a Buildings.Controls.OBC.CDL.* primitive) - preserve
            # the name/description, note the external type, but don't fabricate
            # a Python type for something we never generated a class for.
            note = f"[external type: {sub.block_type_dotted}] {sub.description or ''}".strip()
            return f'{sub.name}: SubBlock = subblock_field(description={note!r})'
        qualified_module = _qualified_module(sub.block_type_dotted)
        alias = sub_aliases.get(sub.block_type_dotted, target.class_name)
        if alias == target.class_name:
            imports.add(f'from {qualified_module} import {target.class_name}')
        else:
            imports.add(f'from {qualified_module} import {target.class_name} as {alias}')
        return (f'{sub.name}: SubBlock = subblock_field('
                f'block_type={alias}, description={sub.description!r})')


def _unit_attr(unit_local: str) -> str:
    """QUDT unit local names aren't always valid Python identifiers
    ('M3-PER-SEC') - qudt/units.py's class names swap '-' for '_'."""
    return unit_local.replace('-', '_')
