"""AUTO-GENERATED by semantic_objects.ingest - DO NOT EDIT.

Source ontology: /Users/lazlopaul/Desktop/HPflex/semantic_objects/.claude/worktrees/watr-ingestion/src/semantic_objects/ontologies/watr/water.ttl
Source SHA256:   21d71d40d0e15d5075f942261964e45278e03ee221b453e561d0fa1450372101
See _meta.py for the generation timestamp.

Regenerate with: python -m semantic_objects.ingest.cli --ontology watr
Hand customizations belong in the sibling non-generated module, which imports from
this one - never edit this file directly, changes will be overwritten.
"""


# Complex SHACL constraints (sh:sparql, sh:or, inverse paths, forbidden properties)
# and supplementary notes on qualified fields, keyed by generated Python class name.
# Preserved for fidelity - not enforced by the framework. See docs/exact_values_generalization.md
# and the ingestion plan for how to hand-implement any of these as real validators.

RAW_SHAPES = {'AerationBasin': [{'comment': None,
                    'field_name': None,
                    'kind': 'other',
                    'message': 'Instances of AerationBasin must have the Aeration process.',
                    'path': 'hasProcess',
                    'raw_turtle': '@prefix sh: <http://www.w3.org/ns/shacl#> .\n'
                                  '@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .\n'
                                  '\n'
                                  '[] sh:hasValue <urn:nawi-water-ontology#Process-Aeration> ;\n'
                                  '    sh:maxCount 1 ;\n'
                                  '    sh:message "Instances of AerationBasin must have the '
                                  'Aeration process."^^xsd:string ;\n'
                                  '    sh:minCount 1 ;\n'
                                  '    sh:path <urn:nawi-water-ontology#hasProcess> .\n'
                                  '\n'},
                   {'comment': None,
                    'field_name': None,
                    'kind': 'other',
                    'message': 'Instances of AerationBasin must have the aerobic role.',
                    'path': 'hasRole',
                    'raw_turtle': '@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .\n'
                                  '@prefix sh: <http://www.w3.org/ns/shacl#> .\n'
                                  '@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .\n'
                                  '\n'
                                  '[] sh:in ( <urn:nawi-water-ontology#Role-Aerobic> '
                                  '<urn:nawi-water-ontology#Role-Anoxic> ) ;\n'
                                  '    sh:message "Instances of AerationBasin must have the '
                                  'aerobic role."^^xsd:string ;\n'
                                  '    sh:minCount 1 ;\n'
                                  '    sh:path <http://data.ashrae.org/standard223#hasRole> .\n'
                                  '\n'}],
 'AerobicDigester': [{'comment': None,
                      'field_name': None,
                      'kind': 'other',
                      'message': 'Instances of AerobicDigester must have the AerobicDigestion '
                                 'process.',
                      'path': 'hasProcess',
                      'raw_turtle': '@prefix sh: <http://www.w3.org/ns/shacl#> .\n'
                                    '@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .\n'
                                    '\n'
                                    '[] sh:hasValue '
                                    '<urn:nawi-water-ontology#Process-AerobicDigestion> ;\n'
                                    '    sh:maxCount 1 ;\n'
                                    '    sh:message "Instances of AerobicDigester must have the '
                                    'AerobicDigestion process."^^xsd:string ;\n'
                                    '    sh:minCount 1 ;\n'
                                    '    sh:path <urn:nawi-water-ontology#hasProcess> .\n'
                                    '\n'}],
 'AnaerobicDigester': [{'comment': None,
                        'field_name': None,
                        'kind': 'other',
                        'message': 'Instances of AnaerobicDigester must have the '
                                   'AnaerobicDigestion process.',
                        'path': 'hasProcess',
                        'raw_turtle': '@prefix sh: <http://www.w3.org/ns/shacl#> .\n'
                                      '@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .\n'
                                      '\n'
                                      '[] sh:hasValue '
                                      '<urn:nawi-water-ontology#Process-AnaerobicDigestion> ;\n'
                                      '    sh:maxCount 1 ;\n'
                                      '    sh:message "Instances of AnaerobicDigester must have '
                                      'the AnaerobicDigestion process."^^xsd:string ;\n'
                                      '    sh:minCount 1 ;\n'
                                      '    sh:path <urn:nawi-water-ontology#hasProcess> .\n'
                                      '\n'}],
 'BeltThickener': [{'comment': None,
                    'field_name': None,
                    'kind': 'other',
                    'message': 'Instances of BeltThickener must have the Filtration process.',
                    'path': 'hasProcess',
                    'raw_turtle': '@prefix sh: <http://www.w3.org/ns/shacl#> .\n'
                                  '@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .\n'
                                  '\n'
                                  '[] sh:hasValue <urn:nawi-water-ontology#Process-Filtration> ;\n'
                                  '    sh:maxCount 1 ;\n'
                                  '    sh:message "Instances of BeltThickener must have the '
                                  'Filtration process."^^xsd:string ;\n'
                                  '    sh:minCount 1 ;\n'
                                  '    sh:path <urn:nawi-water-ontology#hasProcess> .\n'
                                  '\n'}],
 'BiologicalAeratedFilter': [{'comment': None,
                              'field_name': None,
                              'kind': 'other',
                              'message': 'Instances of BiologicalAeratedFilter must have the '
                                         'BiologicallyActiveFiltration process.',
                              'path': 'hasProcess',
                              'raw_turtle': '@prefix sh: <http://www.w3.org/ns/shacl#> .\n'
                                            '@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .\n'
                                            '\n'
                                            '[] sh:hasValue '
                                            '<urn:nawi-water-ontology#Process-BiologicallyActiveFiltration> '
                                            ';\n'
                                            '    sh:maxCount 1 ;\n'
                                            '    sh:message "Instances of BiologicalAeratedFilter '
                                            'must have the BiologicallyActiveFiltration '
                                            'process."^^xsd:string ;\n'
                                            '    sh:minCount 1 ;\n'
                                            '    sh:path <urn:nawi-water-ontology#hasProcess> .\n'
                                            '\n'}],
 'Boiler': [{'comment': None,
             'field_name': None,
             'kind': 'other',
             'message': 'Instances of Boiler must have the Incineration process.',
             'path': 'hasProcess',
             'raw_turtle': '@prefix sh: <http://www.w3.org/ns/shacl#> .\n'
                           '@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .\n'
                           '\n'
                           '[] sh:hasValue <urn:nawi-water-ontology#Process-Incineration> ;\n'
                           '    sh:maxCount 1 ;\n'
                           '    sh:message "Instances of Boiler must have the Incineration '
                           'process."^^xsd:string ;\n'
                           '    sh:minCount 1 ;\n'
                           '    sh:path <urn:nawi-water-ontology#hasProcess> .\n'
                           '\n'}],
 'CentrifugalThickener': [{'comment': None,
                           'field_name': None,
                           'kind': 'other',
                           'message': 'Instances of CentrifugalThickener must have the '
                                      'Centrifugation process.',
                           'path': 'hasProcess',
                           'raw_turtle': '@prefix sh: <http://www.w3.org/ns/shacl#> .\n'
                                         '@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .\n'
                                         '\n'
                                         '[] sh:hasValue '
                                         '<urn:nawi-water-ontology#Process-Centrifugation> ;\n'
                                         '    sh:maxCount 1 ;\n'
                                         '    sh:message "Instances of CentrifugalThickener must '
                                         'have the Centrifugation process."^^xsd:string ;\n'
                                         '    sh:minCount 1 ;\n'
                                         '    sh:path <urn:nawi-water-ontology#hasProcess> .\n'
                                         '\n'}],
 'ChlorinationUnit': [{'comment': None,
                       'field_name': None,
                       'kind': 'other',
                       'message': 'Instances of ChlorinationUnit must have the Chlorination '
                                  'process.',
                       'path': 'hasProcess',
                       'raw_turtle': '@prefix sh: <http://www.w3.org/ns/shacl#> .\n'
                                     '@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .\n'
                                     '\n'
                                     '[] sh:hasValue '
                                     '<urn:nawi-water-ontology#Process-Chlorination> ;\n'
                                     '    sh:maxCount 1 ;\n'
                                     '    sh:message "Instances of ChlorinationUnit must have the '
                                     'Chlorination process."^^xsd:string ;\n'
                                     '    sh:minCount 1 ;\n'
                                     '    sh:path <urn:nawi-water-ontology#hasProcess> .\n'
                                     '\n'}],
 'CoagulationBasin': [{'comment': None,
                       'field_name': None,
                       'kind': 'other',
                       'message': 'Instances of CoagulationBasin must have the Coagulation '
                                  'process.',
                       'path': 'hasProcess',
                       'raw_turtle': '@prefix sh: <http://www.w3.org/ns/shacl#> .\n'
                                     '@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .\n'
                                     '\n'
                                     '[] sh:hasValue <urn:nawi-water-ontology#Process-Coagulation> '
                                     ';\n'
                                     '    sh:maxCount 1 ;\n'
                                     '    sh:message "Instances of CoagulationBasin must have the '
                                     'Coagulation process."^^xsd:string ;\n'
                                     '    sh:minCount 1 ;\n'
                                     '    sh:path <urn:nawi-water-ontology#hasProcess> .\n'
                                     '\n'}],
 'Cogenerator': [{'comment': None,
                  'field_name': None,
                  'kind': 'other',
                  'message': 'Instances of Cogenerator must have the Cogeneration process.',
                  'path': 'hasProcess',
                  'raw_turtle': '@prefix sh: <http://www.w3.org/ns/shacl#> .\n'
                                '@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .\n'
                                '\n'
                                '[] sh:hasValue <urn:nawi-water-ontology#Process-Cogeneration> ;\n'
                                '    sh:maxCount 1 ;\n'
                                '    sh:message "Instances of Cogenerator must have the '
                                'Cogeneration process."^^xsd:string ;\n'
                                '    sh:minCount 1 ;\n'
                                '    sh:path <urn:nawi-water-ontology#hasProcess> .\n'
                                '\n'}],
 'Condenser': [{'comment': None,
                'field_name': None,
                'kind': 'other',
                'message': 'Instances of Condenser must have the Condensation process.',
                'path': 'hasProcess',
                'raw_turtle': '@prefix sh: <http://www.w3.org/ns/shacl#> .\n'
                              '@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .\n'
                              '\n'
                              '[] sh:hasValue <urn:nawi-water-ontology#Process-Condensation> ;\n'
                              '    sh:maxCount 1 ;\n'
                              '    sh:message "Instances of Condenser must have the Condensation '
                              'process."^^xsd:string ;\n'
                              '    sh:minCount 1 ;\n'
                              '    sh:path <urn:nawi-water-ontology#hasProcess> .\n'
                              '\n'}],
 'Crystallizer': [{'comment': None,
                   'field_name': None,
                   'kind': 'other',
                   'message': 'Instances of Crystallizer must have the Crystallization process.',
                   'path': 'hasProcess',
                   'raw_turtle': '@prefix sh: <http://www.w3.org/ns/shacl#> .\n'
                                 '@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .\n'
                                 '\n'
                                 '[] sh:hasValue <urn:nawi-water-ontology#Process-Crystallization> '
                                 ';\n'
                                 '    sh:maxCount 1 ;\n'
                                 '    sh:message "Instances of Crystallizer must have the '
                                 'Crystallization process."^^xsd:string ;\n'
                                 '    sh:minCount 1 ;\n'
                                 '    sh:path <urn:nawi-water-ontology#hasProcess> .\n'
                                 '\n'}],
 'DewateringUnit': [{'comment': None,
                     'field_name': None,
                     'kind': 'other',
                     'message': 'Instances of DewateringUnit must have the Dewatering process.',
                     'path': 'hasProcess',
                     'raw_turtle': '@prefix sh: <http://www.w3.org/ns/shacl#> .\n'
                                   '@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .\n'
                                   '\n'
                                   '[] sh:hasValue <urn:nawi-water-ontology#Process-Dewatering> ;\n'
                                   '    sh:maxCount 1 ;\n'
                                   '    sh:message "Instances of DewateringUnit must have the '
                                   'Dewatering process."^^xsd:string ;\n'
                                   '    sh:minCount 1 ;\n'
                                   '    sh:path <urn:nawi-water-ontology#hasProcess> .\n'
                                   '\n'}],
 'Digester': [{'comment': None,
               'field_name': None,
               'kind': 'other',
               'message': 'Instances of Digester must have the Digestion process.',
               'path': 'hasProcess',
               'raw_turtle': '@prefix sh: <http://www.w3.org/ns/shacl#> .\n'
                             '@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .\n'
                             '\n'
                             '[] sh:hasValue <urn:nawi-water-ontology#Process-Digestion> ;\n'
                             '    sh:maxCount 1 ;\n'
                             '    sh:message "Instances of Digester must have the Digestion '
                             'process."^^xsd:string ;\n'
                             '    sh:minCount 1 ;\n'
                             '    sh:path <urn:nawi-water-ontology#hasProcess> .\n'
                             '\n'}],
 'DisinfectionUnit': [{'comment': None,
                       'field_name': None,
                       'kind': 'other',
                       'message': 'Instances of DisinfectionUnit must have the Disinfection '
                                  'process.',
                       'path': 'hasProcess',
                       'raw_turtle': '@prefix sh: <http://www.w3.org/ns/shacl#> .\n'
                                     '@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .\n'
                                     '\n'
                                     '[] sh:hasValue '
                                     '<urn:nawi-water-ontology#Process-Disinfection> ;\n'
                                     '    sh:maxCount 1 ;\n'
                                     '    sh:message "Instances of DisinfectionUnit must have the '
                                     'Disinfection process."^^xsd:string ;\n'
                                     '    sh:minCount 1 ;\n'
                                     '    sh:path <urn:nawi-water-ontology#hasProcess> .\n'
                                     '\n'}],
 'DissolvedAirFlotationThickener': [{'comment': None,
                                     'field_name': None,
                                     'kind': 'other',
                                     'message': 'Instances of DissolvedAirFlotationThickener must '
                                                'have the Flotation process.',
                                     'path': 'hasProcess',
                                     'raw_turtle': '@prefix sh: <http://www.w3.org/ns/shacl#> .\n'
                                                   '@prefix xsd: '
                                                   '<http://www.w3.org/2001/XMLSchema#> .\n'
                                                   '\n'
                                                   '[] sh:hasValue '
                                                   '<urn:nawi-water-ontology#Process-Flotation> ;\n'
                                                   '    sh:maxCount 1 ;\n'
                                                   '    sh:message "Instances of '
                                                   'DissolvedAirFlotationThickener must have the '
                                                   'Flotation process."^^xsd:string ;\n'
                                                   '    sh:minCount 1 ;\n'
                                                   '    sh:path '
                                                   '<urn:nawi-water-ontology#hasProcess> .\n'
                                                   '\n'}],
 'ElectroDialyticCrystallizer': [{'comment': None,
                                  'field_name': None,
                                  'kind': 'other',
                                  'message': 'Instances of ElectroDialyticCrystallizer must have '
                                             'the Electrodialysis process.',
                                  'path': 'hasProcess',
                                  'raw_turtle': '@prefix sh: <http://www.w3.org/ns/shacl#> .\n'
                                                '@prefix xsd: <http://www.w3.org/2001/XMLSchema#> '
                                                '.\n'
                                                '\n'
                                                '[] sh:hasValue '
                                                '<urn:nawi-water-ontology#Process-Electrodialysis> '
                                                ';\n'
                                                '    sh:maxCount 1 ;\n'
                                                '    sh:message "Instances of '
                                                'ElectroDialyticCrystallizer must have the '
                                                'Electrodialysis process."^^xsd:string ;\n'
                                                '    sh:minCount 1 ;\n'
                                                '    sh:path <urn:nawi-water-ontology#hasProcess> '
                                                '.\n'
                                                '\n'},
                                 {'comment': None,
                                  'field_name': None,
                                  'kind': 'other',
                                  'message': 'Instances of ElectroDialyticCrystallizer must have '
                                             'the Crystallization process.',
                                  'path': 'hasProcess',
                                  'raw_turtle': '@prefix sh: <http://www.w3.org/ns/shacl#> .\n'
                                                '@prefix xsd: <http://www.w3.org/2001/XMLSchema#> '
                                                '.\n'
                                                '\n'
                                                '[] sh:hasValue '
                                                '<urn:nawi-water-ontology#Process-Crystallization> '
                                                ';\n'
                                                '    sh:maxCount 1 ;\n'
                                                '    sh:message "Instances of '
                                                'ElectroDialyticCrystallizer must have the '
                                                'Crystallization process."^^xsd:string ;\n'
                                                '    sh:minCount 1 ;\n'
                                                '    sh:path <urn:nawi-water-ontology#hasProcess> '
                                                '.\n'
                                                '\n'}],
 'ElectrocoagulationUnit': [{'comment': None,
                             'field_name': None,
                             'kind': 'other',
                             'message': 'Instances of ElectrocoagulationUnit must have the '
                                        'Electrocoagulation process.',
                             'path': 'hasProcess',
                             'raw_turtle': '@prefix sh: <http://www.w3.org/ns/shacl#> .\n'
                                           '@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .\n'
                                           '\n'
                                           '[] sh:hasValue '
                                           '<urn:nawi-water-ontology#Process-Electrocoagulation> '
                                           ';\n'
                                           '    sh:maxCount 1 ;\n'
                                           '    sh:message "Instances of ElectrocoagulationUnit '
                                           'must have the Electrocoagulation process."^^xsd:string '
                                           ';\n'
                                           '    sh:minCount 1 ;\n'
                                           '    sh:path <urn:nawi-water-ontology#hasProcess> .\n'
                                           '\n'}],
 'ElectrodialysisUnit': [{'comment': None,
                          'field_name': None,
                          'kind': 'other',
                          'message': 'Instances of ElectrodialysisUnit must have the '
                                     'Electrodialysis process.',
                          'path': 'hasProcess',
                          'raw_turtle': '@prefix sh: <http://www.w3.org/ns/shacl#> .\n'
                                        '@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .\n'
                                        '\n'
                                        '[] sh:hasValue '
                                        '<urn:nawi-water-ontology#Process-Electrodialysis> ;\n'
                                        '    sh:maxCount 1 ;\n'
                                        '    sh:message "Instances of ElectrodialysisUnit must '
                                        'have the Electrodialysis process."^^xsd:string ;\n'
                                        '    sh:minCount 1 ;\n'
                                        '    sh:path <urn:nawi-water-ontology#hasProcess> .\n'
                                        '\n'}],
 'Electrolyzer': [{'comment': None,
                   'field_name': None,
                   'kind': 'other',
                   'message': 'Instances of Electrolyzer must have the Electrolysis process.',
                   'path': 'hasProcess',
                   'raw_turtle': '@prefix sh: <http://www.w3.org/ns/shacl#> .\n'
                                 '@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .\n'
                                 '\n'
                                 '[] sh:hasValue <urn:nawi-water-ontology#Process-Electrolysis> ;\n'
                                 '    sh:maxCount 1 ;\n'
                                 '    sh:message "Instances of Electrolyzer must have the '
                                 'Electrolysis process."^^xsd:string ;\n'
                                 '    sh:minCount 1 ;\n'
                                 '    sh:path <urn:nawi-water-ontology#hasProcess> .\n'
                                 '\n'}],
 'Evaporator': [{'comment': None,
                 'field_name': None,
                 'kind': 'other',
                 'message': 'Instances of Evaporator must have the Evaporation process.',
                 'path': 'hasProcess',
                 'raw_turtle': '@prefix sh: <http://www.w3.org/ns/shacl#> .\n'
                               '@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .\n'
                               '\n'
                               '[] sh:hasValue <urn:nawi-water-ontology#Process-Evaporation> ;\n'
                               '    sh:maxCount 1 ;\n'
                               '    sh:message "Instances of Evaporator must have the Evaporation '
                               'process."^^xsd:string ;\n'
                               '    sh:minCount 1 ;\n'
                               '    sh:path <urn:nawi-water-ontology#hasProcess> .\n'
                               '\n'}],
 'Filter_2': [{'comment': None,
               'field_name': None,
               'kind': 'other',
               'message': 'Instances of Filter must have the Filtration process.',
               'path': 'hasProcess',
               'raw_turtle': '@prefix sh: <http://www.w3.org/ns/shacl#> .\n'
                             '@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .\n'
                             '\n'
                             '[] sh:hasValue <urn:nawi-water-ontology#Process-Filtration> ;\n'
                             '    sh:maxCount 1 ;\n'
                             '    sh:message "Instances of Filter must have the Filtration '
                             'process."^^xsd:string ;\n'
                             '    sh:minCount 1 ;\n'
                             '    sh:path <urn:nawi-water-ontology#hasProcess> .\n'
                             '\n'}],
 'FlocculationBasin': [{'comment': None,
                        'field_name': None,
                        'kind': 'other',
                        'message': 'Instances of FlocculationBasin must have the Flocculation '
                                   'process.',
                        'path': 'hasProcess',
                        'raw_turtle': '@prefix sh: <http://www.w3.org/ns/shacl#> .\n'
                                      '@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .\n'
                                      '\n'
                                      '[] sh:hasValue '
                                      '<urn:nawi-water-ontology#Process-Flocculation> ;\n'
                                      '    sh:maxCount 1 ;\n'
                                      '    sh:message "Instances of FlocculationBasin must have '
                                      'the Flocculation process."^^xsd:string ;\n'
                                      '    sh:minCount 1 ;\n'
                                      '    sh:path <urn:nawi-water-ontology#hasProcess> .\n'
                                      '\n'}],
 'GranularActivatedCarbonAdsorber': [{'comment': None,
                                      'field_name': None,
                                      'kind': 'other',
                                      'message': 'Instances of GranulatedActivatedCarbonAdsorber '
                                                 'must have the GranularActivatedCarbon process.',
                                      'path': 'hasProcess',
                                      'raw_turtle': '@prefix sh: <http://www.w3.org/ns/shacl#> .\n'
                                                    '@prefix xsd: '
                                                    '<http://www.w3.org/2001/XMLSchema#> .\n'
                                                    '\n'
                                                    '[] sh:hasValue '
                                                    '<urn:nawi-water-ontology#Process-GranularActivatedCarbon> '
                                                    ';\n'
                                                    '    sh:maxCount 1 ;\n'
                                                    '    sh:message "Instances of '
                                                    'GranulatedActivatedCarbonAdsorber must have '
                                                    'the GranularActivatedCarbon '
                                                    'process."^^xsd:string ;\n'
                                                    '    sh:minCount 1 ;\n'
                                                    '    sh:path '
                                                    '<urn:nawi-water-ontology#hasProcess> .\n'
                                                    '\n'}],
 'GravityThickener': [{'comment': None,
                       'field_name': None,
                       'kind': 'other',
                       'message': 'Instances of GravityThickener must have the Sedimentation '
                                  'process.',
                       'path': 'hasProcess',
                       'raw_turtle': '@prefix sh: <http://www.w3.org/ns/shacl#> .\n'
                                     '@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .\n'
                                     '\n'
                                     '[] sh:hasValue '
                                     '<urn:nawi-water-ontology#Process-Sedimentation> ;\n'
                                     '    sh:maxCount 1 ;\n'
                                     '    sh:message "Instances of GravityThickener must have the '
                                     'Sedimentation process."^^xsd:string ;\n'
                                     '    sh:minCount 1 ;\n'
                                     '    sh:path <urn:nawi-water-ontology#hasProcess> .\n'
                                     '\n'}],
 'Grinder': [{'comment': None,
              'field_name': None,
              'kind': 'other',
              'message': 'Instances of Grinder must have the Comminution process.',
              'path': 'hasProcess',
              'raw_turtle': '@prefix sh: <http://www.w3.org/ns/shacl#> .\n'
                            '@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .\n'
                            '\n'
                            '[] sh:hasValue <urn:nawi-water-ontology#Process-Comminution> ;\n'
                            '    sh:maxCount 1 ;\n'
                            '    sh:message "Instances of Grinder must have the Comminution '
                            'process."^^xsd:string ;\n'
                            '    sh:minCount 1 ;\n'
                            '    sh:path <urn:nawi-water-ontology#hasProcess> .\n'
                            '\n'}],
 'GritChamber': [{'comment': None,
                  'field_name': None,
                  'kind': 'other',
                  'message': 'Instances of GritChamber must have the Sedimentation process.',
                  'path': 'hasProcess',
                  'raw_turtle': '@prefix sh: <http://www.w3.org/ns/shacl#> .\n'
                                '@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .\n'
                                '\n'
                                '[] sh:hasValue <urn:nawi-water-ontology#Process-Sedimentation> ;\n'
                                '    sh:maxCount 1 ;\n'
                                '    sh:message "Instances of GritChamber must have the '
                                'Sedimentation process."^^xsd:string ;\n'
                                '    sh:minCount 1 ;\n'
                                '    sh:path <urn:nawi-water-ontology#hasProcess> .\n'
                                '\n'}],
 'ImhoffTank': [{'comment': None,
                 'field_name': None,
                 'kind': 'other',
                 'message': 'Instances of ImhoffTank must have the Sedimentation process.',
                 'path': 'hasProcess',
                 'raw_turtle': '@prefix sh: <http://www.w3.org/ns/shacl#> .\n'
                               '@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .\n'
                               '\n'
                               '[] sh:hasValue <urn:nawi-water-ontology#Process-Sedimentation> ;\n'
                               '    sh:maxCount 1 ;\n'
                               '    sh:message "Instances of ImhoffTank must have the '
                               'Sedimentation process."^^xsd:string ;\n'
                               '    sh:minCount 1 ;\n'
                               '    sh:path <urn:nawi-water-ontology#hasProcess> .\n'
                               '\n'}],
 'IonExchangeMembrane': [{'comment': None,
                          'field_name': None,
                          'kind': 'other',
                          'message': 'Instances of IonExchangeMembrane must have the IonExchange '
                                     'process.',
                          'path': 'hasProcess',
                          'raw_turtle': '@prefix sh: <http://www.w3.org/ns/shacl#> .\n'
                                        '@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .\n'
                                        '\n'
                                        '[] sh:hasValue '
                                        '<urn:nawi-water-ontology#Process-IonExchange> ;\n'
                                        '    sh:maxCount 1 ;\n'
                                        '    sh:message "Instances of IonExchangeMembrane must '
                                        'have the IonExchange process."^^xsd:string ;\n'
                                        '    sh:minCount 1 ;\n'
                                        '    sh:path <urn:nawi-water-ontology#hasProcess> .\n'
                                        '\n'}],
 'MediaFiltration': [{'comment': None,
                      'field_name': None,
                      'kind': 'other',
                      'message': 'Instances of MediaFiltration must have the MediaFiltration '
                                 'process.',
                      'path': 'hasProcess',
                      'raw_turtle': '@prefix sh: <http://www.w3.org/ns/shacl#> .\n'
                                    '@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .\n'
                                    '\n'
                                    '[] sh:hasValue '
                                    '<urn:nawi-water-ontology#Process-MediaFiltration> ;\n'
                                    '    sh:maxCount 1 ;\n'
                                    '    sh:message "Instances of MediaFiltration must have the '
                                    'MediaFiltration process."^^xsd:string ;\n'
                                    '    sh:minCount 1 ;\n'
                                    '    sh:path <urn:nawi-water-ontology#hasProcess> .\n'
                                    '\n'}],
 'MembraneAeratedBiofilmReaactor': [{'comment': None,
                                     'field_name': None,
                                     'kind': 'other',
                                     'message': 'Instances of MembraneAeratedBiofilmReaactor must '
                                                'have the Aeration process.',
                                     'path': 'hasProcess',
                                     'raw_turtle': '@prefix sh: <http://www.w3.org/ns/shacl#> .\n'
                                                   '@prefix xsd: '
                                                   '<http://www.w3.org/2001/XMLSchema#> .\n'
                                                   '\n'
                                                   '[] sh:hasValue '
                                                   '<urn:nawi-water-ontology#Process-Aeration> ;\n'
                                                   '    sh:maxCount 1 ;\n'
                                                   '    sh:message "Instances of '
                                                   'MembraneAeratedBiofilmReaactor must have the '
                                                   'Aeration process."^^xsd:string ;\n'
                                                   '    sh:minCount 1 ;\n'
                                                   '    sh:path '
                                                   '<urn:nawi-water-ontology#hasProcess> .\n'
                                                   '\n'}],
 'MembraneBioreactor': [{'comment': None,
                         'field_name': None,
                         'kind': 'other',
                         'message': 'Instances of MembraneBioreactor must have either the '
                                    'Microfiltration or Ultrafiltration process.',
                         'path': 'hasProcess',
                         'raw_turtle': '@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> '
                                       '.\n'
                                       '@prefix sh: <http://www.w3.org/ns/shacl#> .\n'
                                       '@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .\n'
                                       '\n'
                                       '[] sh:in ( '
                                       '<urn:nawi-water-ontology#Process-Microfiltration> '
                                       '<urn:nawi-water-ontology#Process-Ultrafiltration> ) ;\n'
                                       '    sh:maxCount 1 ;\n'
                                       '    sh:message "Instances of MembraneBioreactor must have '
                                       'either the Microfiltration or Ultrafiltration '
                                       'process."^^xsd:string ;\n'
                                       '    sh:minCount 1 ;\n'
                                       '    sh:path <urn:nawi-water-ontology#hasProcess> .\n'
                                       '\n'},
                        {'comment': None,
                         'field_name': None,
                         'kind': 'other',
                         'message': 'Instances of MembraneBioreactor must have the Biofiltration '
                                    'process.',
                         'path': 'hasProcess',
                         'raw_turtle': '@prefix sh: <http://www.w3.org/ns/shacl#> .\n'
                                       '@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .\n'
                                       '\n'
                                       '[] sh:hasValue '
                                       '<urn:nawi-water-ontology#Process-Biofiltration> ;\n'
                                       '    sh:maxCount 1 ;\n'
                                       '    sh:message "Instances of MembraneBioreactor must have '
                                       'the Biofiltration process."^^xsd:string ;\n'
                                       '    sh:minCount 1 ;\n'
                                       '    sh:path <urn:nawi-water-ontology#hasProcess> .\n'
                                       '\n'}],
 'MicrofiltrationUnit': [{'comment': None,
                          'field_name': None,
                          'kind': 'other',
                          'message': 'Instances of MicrofiltrationUnit must have the '
                                     'Microfiltration process.',
                          'path': 'hasProcess',
                          'raw_turtle': '@prefix sh: <http://www.w3.org/ns/shacl#> .\n'
                                        '@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .\n'
                                        '\n'
                                        '[] sh:hasValue '
                                        '<urn:nawi-water-ontology#Process-Microfiltration> ;\n'
                                        '    sh:maxCount 1 ;\n'
                                        '    sh:message "Instances of MicrofiltrationUnit must '
                                        'have the Microfiltration process."^^xsd:string ;\n'
                                        '    sh:minCount 1 ;\n'
                                        '    sh:path <urn:nawi-water-ontology#hasProcess> .\n'
                                        '\n'}],
 'MixingBasin': [{'comment': None,
                  'field_name': None,
                  'kind': 'other',
                  'message': 'Instances of MixingBasin must have the anoxic or anaerobic role.',
                  'path': 'hasRole',
                  'raw_turtle': '@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .\n'
                                '@prefix sh: <http://www.w3.org/ns/shacl#> .\n'
                                '@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .\n'
                                '\n'
                                '[] sh:in ( <urn:nawi-water-ontology#Role-Anoxic> '
                                '<urn:nawi-water-ontology#Role-Anaerobic> ) ;\n'
                                '    sh:message "Instances of MixingBasin must have the anoxic or '
                                'anaerobic role."^^xsd:string ;\n'
                                '    sh:minCount 1 ;\n'
                                '    sh:path <http://data.ashrae.org/standard223#hasRole> .\n'
                                '\n'},
                 {'comment': None,
                  'field_name': None,
                  'kind': 'other',
                  'message': 'Instances of MixingBasin must have the Mixing process.',
                  'path': 'hasProcess',
                  'raw_turtle': '@prefix sh: <http://www.w3.org/ns/shacl#> .\n'
                                '@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .\n'
                                '\n'
                                '[] sh:hasValue <urn:nawi-water-ontology#Process-Mixing> ;\n'
                                '    sh:maxCount 1 ;\n'
                                '    sh:message "Instances of MixingBasin must have the Mixing '
                                'process."^^xsd:string ;\n'
                                '    sh:minCount 1 ;\n'
                                '    sh:path <urn:nawi-water-ontology#hasProcess> .\n'
                                '\n'}],
 'OxidationDitch': [{'comment': None,
                     'field_name': None,
                     'kind': 'other',
                     'message': 'Instances of OxidationDitch must have the ActivatedSludge '
                                'process.',
                     'path': 'hasProcess',
                     'raw_turtle': '@prefix sh: <http://www.w3.org/ns/shacl#> .\n'
                                   '@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .\n'
                                   '\n'
                                   '[] sh:hasValue '
                                   '<urn:nawi-water-ontology#Process-ActivatedSludge> ;\n'
                                   '    sh:maxCount 1 ;\n'
                                   '    sh:message "Instances of OxidationDitch must have the '
                                   'ActivatedSludge process."^^xsd:string ;\n'
                                   '    sh:minCount 1 ;\n'
                                   '    sh:path <urn:nawi-water-ontology#hasProcess> .\n'
                                   '\n'}],
 'OzonationUnit': [{'comment': None,
                    'field_name': None,
                    'kind': 'other',
                    'message': 'Instances of OzonationUnit must have the Ozonation process.',
                    'path': 'hasProcess',
                    'raw_turtle': '@prefix sh: <http://www.w3.org/ns/shacl#> .\n'
                                  '@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .\n'
                                  '\n'
                                  '[] sh:hasValue <urn:nawi-water-ontology#Process-Ozonation> ;\n'
                                  '    sh:maxCount 1 ;\n'
                                  '    sh:message "Instances of OzonationUnit must have the '
                                  'Ozonation process."^^xsd:string ;\n'
                                  '    sh:minCount 1 ;\n'
                                  '    sh:path <urn:nawi-water-ontology#hasProcess> .\n'
                                  '\n'}],
 'PlugFlowReactor': [{'comment': 'Additional constraints on the qualified value beyond its class '
                                 '(medium, sub-shape, etc.) - see raw_turtle.',
                      'field_name': 'outlet_connection_point',
                      'kind': 'nested-node',
                      'message': None,
                      'path': 'hasConnectionPoint',
                      'raw_turtle': '@prefix sh: <http://www.w3.org/ns/shacl#> .\n'
                                    '\n'
                                    '[] sh:class '
                                    '<http://data.ashrae.org/standard223#OutletConnectionPoint> ;\n'
                                    '    sh:property [ sh:hasValue '
                                    '<http://data.ashrae.org/standard223#Mix-Fluid> ;\n'
                                    '            sh:path '
                                    '<http://data.ashrae.org/standard223#hasMedium> ] .\n'
                                    '\n'},
                     {'comment': 'Additional constraints on the qualified value beyond its class '
                                 '(medium, sub-shape, etc.) - see raw_turtle.',
                      'field_name': 'inlet_connection_point',
                      'kind': 'nested-node',
                      'message': None,
                      'path': 'hasConnectionPoint',
                      'raw_turtle': '@prefix sh: <http://www.w3.org/ns/shacl#> .\n'
                                    '\n'
                                    '[] sh:class '
                                    '<http://data.ashrae.org/standard223#InletConnectionPoint> ;\n'
                                    '    sh:property [ sh:hasValue '
                                    '<http://data.ashrae.org/standard223#Mix-Fluid> ;\n'
                                    '            sh:path '
                                    '<http://data.ashrae.org/standard223#hasMedium> ] .\n'
                                    '\n'}],
 'ProcessType': [{'comment': None,
                  'datatype_local': 'string',
                  'field_name': 'label',
                  'kind': 'relation-out-of-scope',
                  'max_count': 1,
                  'min_count': 1,
                  'path': 'label',
                  'qualified': False,
                  'target_class_local': None},
                 {'comment': None,
                  'datatype_local': 'string',
                  'field_name': 'definition',
                  'kind': 'relation-out-of-scope',
                  'max_count': 1,
                  'min_count': 1,
                  'path': 'definition',
                  'qualified': False,
                  'target_class_local': None}],
 'RapidSandFilter': [{'comment': None,
                      'field_name': None,
                      'kind': 'other',
                      'message': 'Instances of RapidSandFilter must have the RapidSandFiltration '
                                 'process.',
                      'path': 'hasProcess',
                      'raw_turtle': '@prefix sh: <http://www.w3.org/ns/shacl#> .\n'
                                    '@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .\n'
                                    '\n'
                                    '[] sh:hasValue '
                                    '<urn:nawi-water-ontology#Process-RapidSandFiltration> ;\n'
                                    '    sh:maxCount 1 ;\n'
                                    '    sh:message "Instances of RapidSandFilter must have the '
                                    'RapidSandFiltration process."^^xsd:string ;\n'
                                    '    sh:minCount 1 ;\n'
                                    '    sh:path <urn:nawi-water-ontology#hasProcess> .\n'
                                    '\n'}],
 'Reactor': [{'comment': 'Additional constraints on the qualified value beyond its class (medium, '
                         'sub-shape, etc.) - see raw_turtle.',
              'field_name': 'outlet_connection_point',
              'kind': 'nested-node',
              'message': None,
              'path': 'hasConnectionPoint',
              'raw_turtle': '@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .\n'
                            '@prefix sh: <http://www.w3.org/ns/shacl#> .\n'
                            '\n'
                            '[] sh:class '
                            '<http://data.ashrae.org/standard223#OutletConnectionPoint> ;\n'
                            '    sh:property [ sh:in ( '
                            '<http://data.ashrae.org/standard223#Role-Recirculating> '
                            '<http://data.ashrae.org/standard223#Role-Return> ) ;\n'
                            '            sh:path <http://data.ashrae.org/standard223#hasRole> ],\n'
                            '        [ sh:hasValue <http://data.ashrae.org/standard223#Mix-Fluid> '
                            ';\n'
                            '            sh:path <http://data.ashrae.org/standard223#hasMedium> ] '
                            '.\n'
                            '\n'}],
 'ReverseOsmosisMembrane': [{'comment': None,
                             'field_name': None,
                             'kind': 'other',
                             'message': 'Instances of ReverseOsmosisMembrane must have the '
                                        'ReverseOsmosis process.',
                             'path': 'hasProcess',
                             'raw_turtle': '@prefix sh: <http://www.w3.org/ns/shacl#> .\n'
                                           '@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .\n'
                                           '\n'
                                           '[] sh:hasValue '
                                           '<urn:nawi-water-ontology#Process-ReverseOsmosis> ;\n'
                                           '    sh:maxCount 1 ;\n'
                                           '    sh:message "Instances of ReverseOsmosisMembrane '
                                           'must have the ReverseOsmosis process."^^xsd:string ;\n'
                                           '    sh:minCount 1 ;\n'
                                           '    sh:path <urn:nawi-water-ontology#hasProcess> .\n'
                                           '\n'}],
 'RotaryDrumThickener': [{'comment': None,
                          'field_name': None,
                          'kind': 'other',
                          'message': 'Instances of RotaryDrumThickener must have the Filtration '
                                     'process.',
                          'path': 'hasProcess',
                          'raw_turtle': '@prefix sh: <http://www.w3.org/ns/shacl#> .\n'
                                        '@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .\n'
                                        '\n'
                                        '[] sh:hasValue '
                                        '<urn:nawi-water-ontology#Process-Filtration> ;\n'
                                        '    sh:maxCount 1 ;\n'
                                        '    sh:message "Instances of RotaryDrumThickener must '
                                        'have the Filtration process."^^xsd:string ;\n'
                                        '    sh:minCount 1 ;\n'
                                        '    sh:path <urn:nawi-water-ontology#hasProcess> .\n'
                                        '\n'}],
 'RotatingBiologicalContactor': [{'comment': None,
                                  'field_name': None,
                                  'kind': 'other',
                                  'message': 'Instances of RotatingBiologicalContactor must have '
                                             'the Biofiltration process.',
                                  'path': 'hasProcess',
                                  'raw_turtle': '@prefix sh: <http://www.w3.org/ns/shacl#> .\n'
                                                '@prefix xsd: <http://www.w3.org/2001/XMLSchema#> '
                                                '.\n'
                                                '\n'
                                                '[] sh:hasValue '
                                                '<urn:nawi-water-ontology#Process-Biofiltration> '
                                                ';\n'
                                                '    sh:maxCount 1 ;\n'
                                                '    sh:message "Instances of '
                                                'RotatingBiologicalContactor must have the '
                                                'Biofiltration process."^^xsd:string ;\n'
                                                '    sh:minCount 1 ;\n'
                                                '    sh:path <urn:nawi-water-ontology#hasProcess> '
                                                '.\n'
                                                '\n'}],
 'Screen': [{'comment': None,
             'field_name': None,
             'kind': 'other',
             'message': 'Instances of Screen must have the Screening process.',
             'path': 'hasProcess',
             'raw_turtle': '@prefix sh: <http://www.w3.org/ns/shacl#> .\n'
                           '@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .\n'
                           '\n'
                           '[] sh:hasValue <urn:nawi-water-ontology#Process-Screening> ;\n'
                           '    sh:maxCount 1 ;\n'
                           '    sh:message "Instances of Screen must have the Screening '
                           'process."^^xsd:string ;\n'
                           '    sh:minCount 1 ;\n'
                           '    sh:path <urn:nawi-water-ontology#hasProcess> .\n'
                           '\n'}],
 'SedimentationTank': [{'comment': None,
                        'field_name': None,
                        'kind': 'other',
                        'message': 'Instances of SedimentationTank must have the Sedimentation '
                                   'process.',
                        'path': 'hasProcess',
                        'raw_turtle': '@prefix sh: <http://www.w3.org/ns/shacl#> .\n'
                                      '@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .\n'
                                      '\n'
                                      '[] sh:hasValue '
                                      '<urn:nawi-water-ontology#Process-Sedimentation> ;\n'
                                      '    sh:maxCount 1 ;\n'
                                      '    sh:message "Instances of SedimentationTank must have '
                                      'the Sedimentation process."^^xsd:string ;\n'
                                      '    sh:minCount 1 ;\n'
                                      '    sh:path <urn:nawi-water-ontology#hasProcess> .\n'
                                      '\n'}],
 'SeparationTank': [{'comment': 'Additional constraints on the qualified value beyond its class '
                                '(medium, sub-shape, etc.) - see raw_turtle.',
                     'field_name': 'outlet_connection_point',
                     'kind': 'nested-node',
                     'message': None,
                     'path': 'hasConnectionPoint',
                     'raw_turtle': '@prefix sh: <http://www.w3.org/ns/shacl#> .\n'
                                   '\n'
                                   '[] sh:class '
                                   '<http://data.ashrae.org/standard223#OutletConnectionPoint> ;\n'
                                   '    sh:property [ sh:hasValue '
                                   '<http://data.ashrae.org/standard223#Mix-Fluid> ;\n'
                                   '            sh:path '
                                   '<http://data.ashrae.org/standard223#hasMedium> ] .\n'
                                   '\n'},
                    {'comment': None,
                     'field_name': None,
                     'kind': 'other',
                     'message': 'Instances of SeparationTank must have the Separation process.',
                     'path': 'hasProcess',
                     'raw_turtle': '@prefix sh: <http://www.w3.org/ns/shacl#> .\n'
                                   '@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .\n'
                                   '\n'
                                   '[] sh:hasValue <urn:nawi-water-ontology#Process-Separation> ;\n'
                                   '    sh:maxCount 1 ;\n'
                                   '    sh:message "Instances of SeparationTank must have the '
                                   'Separation process."^^xsd:string ;\n'
                                   '    sh:minCount 1 ;\n'
                                   '    sh:path <urn:nawi-water-ontology#hasProcess> .\n'
                                   '\n'}],
 'SequencingBatchReactor': [{'comment': 'Additional constraints on the qualified value beyond its '
                                        'class (medium, sub-shape, etc.) - see raw_turtle.',
                             'field_name': 'outlet_connection_point',
                             'kind': 'nested-node',
                             'message': None,
                             'path': 'hasConnectionPoint',
                             'raw_turtle': '@prefix sh: <http://www.w3.org/ns/shacl#> .\n'
                                           '\n'
                                           '[] sh:class '
                                           '<http://data.ashrae.org/standard223#OutletConnectionPoint> '
                                           ';\n'
                                           '    sh:property [ sh:hasValue '
                                           '<http://data.ashrae.org/standard223#Fluid-Sludge> ;\n'
                                           '            sh:path '
                                           '<http://data.ashrae.org/standard223#hasMedium> ] .\n'
                                           '\n'},
                            {'comment': None,
                             'field_name': None,
                             'kind': 'other',
                             'message': 'Instances of SequencingBatchReactor must have the '
                                        'ActivatedSludge process.',
                             'path': 'hasProcess',
                             'raw_turtle': '@prefix sh: <http://www.w3.org/ns/shacl#> .\n'
                                           '@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .\n'
                                           '\n'
                                           '[] sh:hasValue '
                                           '<urn:nawi-water-ontology#Process-ActivatedSludge> ;\n'
                                           '    sh:maxCount 1 ;\n'
                                           '    sh:message "Instances of SequencingBatchReactor '
                                           'must have the ActivatedSludge process."^^xsd:string ;\n'
                                           '    sh:minCount 1 ;\n'
                                           '    sh:path <urn:nawi-water-ontology#hasProcess> .\n'
                                           '\n'}],
 'SolventExtractionSystem': [{'comment': None,
                              'field_name': None,
                              'kind': 'other',
                              'message': 'Instances of SolventExtractionSystem must have the '
                                         'SolventExtraction process.',
                              'path': 'hasProcess',
                              'raw_turtle': '@prefix sh: <http://www.w3.org/ns/shacl#> .\n'
                                            '@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .\n'
                                            '\n'
                                            '[] sh:hasValue '
                                            '<urn:nawi-water-ontology#Process-SolventExtraction> '
                                            ';\n'
                                            '    sh:maxCount 1 ;\n'
                                            '    sh:message "Instances of SolventExtractionSystem '
                                            'must have the SolventExtraction process."^^xsd:string '
                                            ';\n'
                                            '    sh:minCount 1 ;\n'
                                            '    sh:path <urn:nawi-water-ontology#hasProcess> .\n'
                                            '\n'}],
 'StaticMixer': [{'comment': None,
                  'field_name': None,
                  'kind': 'other',
                  'message': 'Instances of StaticMixer must have the Mixing process.',
                  'path': 'hasProcess',
                  'raw_turtle': '@prefix sh: <http://www.w3.org/ns/shacl#> .\n'
                                '@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .\n'
                                '\n'
                                '[] sh:hasValue <urn:nawi-water-ontology#Process-Mixing> ;\n'
                                '    sh:maxCount 1 ;\n'
                                '    sh:message "Instances of StaticMixer must have the Mixing '
                                'process."^^xsd:string ;\n'
                                '    sh:minCount 1 ;\n'
                                '    sh:path <urn:nawi-water-ontology#hasProcess> .\n'
                                '\n'}],
 'Tank': [{'comment': 'Additional constraints on the qualified value beyond its class (medium, '
                      'sub-shape, etc.) - see raw_turtle.',
           'field_name': 'outlet_connection_point',
           'kind': 'nested-node',
           'message': None,
           'path': 'hasConnectionPoint',
           'raw_turtle': '@prefix sh: <http://www.w3.org/ns/shacl#> .\n'
                         '@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .\n'
                         '\n'
                         '[] sh:class <http://data.ashrae.org/standard223#OutletConnectionPoint> '
                         ';\n'
                         '    sh:not [ sh:property [ sh:hasValue '
                         '<urn:nawi-water-ontology#Role-Drain> ;\n'
                         '                    sh:minCount 1 ;\n'
                         '                    sh:path <http://data.ashrae.org/standard223#hasRole> '
                         '] ] ;\n'
                         '    sh:property [ sh:hasValue '
                         '<http://data.ashrae.org/standard223#Mix-Fluid> ;\n'
                         '            sh:path <http://data.ashrae.org/standard223#hasMedium> ] .\n'
                         '\n'},
          {'comment': 'Additional constraints on the qualified value beyond its class (medium, '
                      'sub-shape, etc.) - see raw_turtle.',
           'field_name': 'outlet_connection_point_2',
           'kind': 'nested-node',
           'message': None,
           'path': 'hasConnectionPoint',
           'raw_turtle': '@prefix sh: <http://www.w3.org/ns/shacl#> .\n'
                         '\n'
                         '[] sh:class <http://data.ashrae.org/standard223#OutletConnectionPoint> '
                         ';\n'
                         '    sh:property [ sh:hasValue '
                         '<http://data.ashrae.org/standard223#Role-Overflow> ;\n'
                         '            sh:path <http://data.ashrae.org/standard223#hasRole> ],\n'
                         '        [ sh:hasValue <http://data.ashrae.org/standard223#Mix-Fluid> ;\n'
                         '            sh:path <http://data.ashrae.org/standard223#hasMedium> ] .\n'
                         '\n'},
          {'comment': 'Additional constraints on the qualified value beyond its class (medium, '
                      'sub-shape, etc.) - see raw_turtle.',
           'field_name': 'outlet_connection_point_3',
           'kind': 'nested-node',
           'message': None,
           'path': 'hasConnectionPoint',
           'raw_turtle': '@prefix sh: <http://www.w3.org/ns/shacl#> .\n'
                         '\n'
                         '[] sh:class <http://data.ashrae.org/standard223#OutletConnectionPoint> '
                         ';\n'
                         '    sh:property [ sh:hasValue <urn:nawi-water-ontology#Role-Drain> ;\n'
                         '            sh:path <http://data.ashrae.org/standard223#hasRole> ],\n'
                         '        [ sh:hasValue <http://data.ashrae.org/standard223#Mix-Fluid> ;\n'
                         '            sh:path <http://data.ashrae.org/standard223#hasMedium> ] .\n'
                         '\n'},
          {'comment': 'Additional constraints on the qualified value beyond its class (medium, '
                      'sub-shape, etc.) - see raw_turtle.',
           'field_name': 'inlet_connection_point',
           'kind': 'nested-node',
           'message': None,
           'path': 'hasConnectionPoint',
           'raw_turtle': '@prefix sh: <http://www.w3.org/ns/shacl#> .\n'
                         '\n'
                         '[] sh:class <http://data.ashrae.org/standard223#InletConnectionPoint> ;\n'
                         '    sh:property [ sh:hasValue '
                         '<http://data.ashrae.org/standard223#Mix-Fluid> ;\n'
                         '            sh:path <http://data.ashrae.org/standard223#hasMedium> ] .\n'
                         '\n'}],
 'TricklingFilter': [{'comment': None,
                      'field_name': None,
                      'kind': 'other',
                      'message': 'Instances of TricklingFilter must have the TricklingFiltration '
                                 'process.',
                      'path': 'hasProcess',
                      'raw_turtle': '@prefix sh: <http://www.w3.org/ns/shacl#> .\n'
                                    '@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .\n'
                                    '\n'
                                    '[] sh:hasValue '
                                    '<urn:nawi-water-ontology#Process-TricklingFiltration> ;\n'
                                    '    sh:maxCount 1 ;\n'
                                    '    sh:message "Instances of TricklingFilter must have the '
                                    'TricklingFiltration process."^^xsd:string ;\n'
                                    '    sh:minCount 1 ;\n'
                                    '    sh:path <urn:nawi-water-ontology#hasProcess> .\n'
                                    '\n'}],
 'UVH2O2Reactor': [{'comment': None,
                    'field_name': None,
                    'kind': 'other',
                    'message': 'Instances of UVH2O2Reactor must have the AdvancedOxidation '
                               'process.',
                    'path': 'hasProcess',
                    'raw_turtle': '@prefix sh: <http://www.w3.org/ns/shacl#> .\n'
                                  '@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .\n'
                                  '\n'
                                  '[] sh:hasValue '
                                  '<urn:nawi-water-ontology#Process-AdvancedOxidation> ;\n'
                                  '    sh:maxCount 1 ;\n'
                                  '    sh:message "Instances of UVH2O2Reactor must have the '
                                  'AdvancedOxidation process."^^xsd:string ;\n'
                                  '    sh:minCount 1 ;\n'
                                  '    sh:path <urn:nawi-water-ontology#hasProcess> .\n'
                                  '\n'}],
 'UltrafiltrationUnit': [{'comment': None,
                          'field_name': None,
                          'kind': 'other',
                          'message': 'Instances of UltrafiltrationUnit must have the '
                                     'Ultrafiltration process.',
                          'path': 'hasProcess',
                          'raw_turtle': '@prefix sh: <http://www.w3.org/ns/shacl#> .\n'
                                        '@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .\n'
                                        '\n'
                                        '[] sh:hasValue '
                                        '<urn:nawi-water-ontology#Process-Ultrafiltration> ;\n'
                                        '    sh:maxCount 1 ;\n'
                                        '    sh:message "Instances of UltrafiltrationUnit must '
                                        'have the Ultrafiltration process."^^xsd:string ;\n'
                                        '    sh:minCount 1 ;\n'
                                        '    sh:path <urn:nawi-water-ontology#hasProcess> .\n'
                                        '\n'}],
 'UltravioletLightUnit': [{'comment': None,
                           'field_name': None,
                           'kind': 'other',
                           'message': 'Instances of UltravioletLightUnit must have the '
                                      'UVDisinfection process.',
                           'path': 'hasProcess',
                           'raw_turtle': '@prefix sh: <http://www.w3.org/ns/shacl#> .\n'
                                         '@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .\n'
                                         '\n'
                                         '[] sh:hasValue '
                                         '<urn:nawi-water-ontology#Process-UVDisinfection> ;\n'
                                         '    sh:maxCount 1 ;\n'
                                         '    sh:message "Instances of UltravioletLightUnit must '
                                         'have the UVDisinfection process."^^xsd:string ;\n'
                                         '    sh:minCount 1 ;\n'
                                         '    sh:path <urn:nawi-water-ontology#hasProcess> .\n'
                                         '\n'}],
 'UnitProcess': [{'comment': None,
                  'datatype_local': None,
                  'field_name': 'process',
                  'kind': 'unresolved-target',
                  'max_count': None,
                  'min_count': 1,
                  'path': 'hasProcess',
                  'qualified': False,
                  'target_class_local': 'Process'}]}
