"""AUTO-GENERATED by semantic_objects.ingest - DO NOT EDIT.

Source ontology: /Users/lazlopaul/Desktop/HPflex/semantic_objects/.claude/worktrees/watr-ingestion/src/semantic_objects/ontologies/watr/water.ttl
Source SHA256:   21d71d40d0e15d5075f942261964e45278e03ee221b453e561d0fa1450372101
See _meta.py for the generation timestamp.

Regenerate with: python -m semantic_objects.ingest.cli --ontology watr
Hand customizations belong in the sibling non-generated module, which imports from
this one - never edit this file directly, changes will be overwritten.
"""

from typing import Self
from ...core import *
from ..core import Node, EnumerationKind, ExternalReference
from . import relations
from ...qudt import Unit, QuantityKind
from ... import s223
__all__ = []

