"""AUTO-GENERATED by semantic_objects.ingest - DO NOT EDIT.

Source ontology: /Users/lazlopaul/Desktop/HPflex/semantic_objects/.claude/worktrees/watr-ingestion/src/semantic_objects/ontologies/watr/water.ttl
Source SHA256:   21d71d40d0e15d5075f942261964e45278e03ee221b453e561d0fa1450372101
See _meta.py for the generation timestamp.

Regenerate with: python -m semantic_objects.ingest.cli --ontology watr
Hand customizations belong in the sibling non-generated module, which imports from
this one - never edit this file directly, changes will be overwritten.
"""

from ...core import semantic_object, Predicate as _CorePredicate
from ...namespaces import WATR
__all__ = ['Predicate', 'hasAccuracy', 'hasAggregation', 'hasBias', 'hasCalibrationCurve', 'hasDropRate', 'hasMeasurementRange', 'hasNumericRange', 'hasNumericResolution', 'hasPrecision', 'hasProcess', 'hasProcessedData', 'hasResponseTime', 'hasTemporalRange', 'hasTemporalResolution', 'hasVariableRange']

@semantic_object
class Predicate(_CorePredicate):
    _ns = WATR

@semantic_object
class hasAccuracy(Predicate):
    label = 'has accuracy'
    comment = 'The `hasAccuracy` relation is used to link to a numerical `Property` whose value indicates the maximum expected deviation between the measured value and the true value in engineering units.'

@semantic_object
class hasAggregation(Predicate):
    label = 'has aggregation'
    comment = 'The `hasAggregation` relation associates a property with water-specific aggregation semantics such as total, mean, maximum, or minimum.'

@semantic_object
class hasBias(Predicate):
    label = 'has bias'
    comment = 'The `hasBias` relation is used to link to a numerical `Property` whose value indicates the systematic offset or drift in measurements relative to the true value.'

@semantic_object
class hasCalibrationCurve(Predicate):
    label = 'has calibration curve'
    comment = 'The `hasCalibrationCurve` relation is used to link to a `Property` that describes the mathematical relationship or lookup table between raw sensor output and calibrated engineering units.'

@semantic_object
class hasDropRate(Predicate):
    label = 'has drop rate'
    comment = 'The `hasDropRate` relation is used to link to a `Property` describes the amount of data points lost within a range of time due to latencies or other factors.'

@semantic_object
class hasMeasurementRange(Predicate):
    label = 'has measurement range'
    comment = 'The `hasMeasurementRange` relation is used to link to a numerical `Property` whose value indicates the expected range of variation that can physically be measured, e.g. by a sensor.'

@semantic_object
class hasNumericRange(Predicate):
    label = 'has numeric range'
    comment = 'The `hasNumericRange` relation is used to link to a numerical `Property` whose value indicates the span between the minimum and maximum measurable values in engineering units.'

@semantic_object
class hasNumericResolution(Predicate):
    label = 'has numeric resolution'
    comment = 'The `hasNumericResolution` relation is used to link to a numerical `Property` whose value indicates the smallest distinguishable difference between two measured values in engineering units.'

@semantic_object
class hasPrecision(Predicate):
    label = 'has precision'
    comment = 'The `hasPrecision` relation is used to link to a numerical `Property` whose value indicates the repeatability or reproducibility of measurements under identical conditions.'

@semantic_object
class hasProcess(Predicate):
    label = 'has process'
    comment = 'This property is used to associate a water treatment process with a piece of equipment.'

@semantic_object
class hasProcessedData(Predicate):
    label = 'has processed data'
    comment = 'The `hasProcessedData` relation is used to link to a `Property` that describes any data processing, filtering, or transformation applied to the raw measurement values.'

@semantic_object
class hasResponseTime(Predicate):
    label = 'has response time'
    comment = 'The `hasResponseTime` relation is used to link to a numerical `Property` whose value indicates the time required for the sensor or measurement system to respond to a step change in the measured variable.'

@semantic_object
class hasTemporalRange(Predicate):
    label = 'has temporal range'
    comment = 'The `hasTemporalRange` relation is used to link to a numerical `Property` whose value indicates the start and end times for which data has been recorded.'

@semantic_object
class hasTemporalResolution(Predicate):
    label = 'has temporal resolution'
    comment = 'The `hasTemporalResolution` relation is used to link to a numerical `Property` whose value indicates the minimum time interval between successive measurements or data points.'

@semantic_object
class hasVariableRange(Predicate):
    label = 'has variable range'
    comment = 'The `hasVariableRange` relation is used to link to a numerical `Property` whose value indicates the expected range of variation for the measured variable under normal operating conditions.'
