"""AUTO-GENERATED by semantic_objects.ingest - DO NOT EDIT.

Source ontology: /Users/lazlopaul/Desktop/223p/experiments/semantic_objects/.claude/worktrees/cxf-ingestion/src/semantic_objects/ontologies/cxf/Buildings/Controls/OBC/ASHRAE/G36
Source file count SHA256: 381dac3f5fd40eceed32194ddebbd66207c6b6dede645138bc98ffa4913510cc

Regenerate with: python -m semantic_objects.ingest.cli --ontology cxf
Hand customizations belong in the sibling non-generated module, which imports
from this one - never edit this file directly, changes will be overwritten.
"""


SOURCE_DIR = '/Users/lazlopaul/Desktop/223p/experiments/semantic_objects/.claude/worktrees/cxf-ingestion/src/semantic_objects/ontologies/cxf/Buildings/Controls/OBC/ASHRAE/G36'

SOURCE_SHA256 = '381dac3f5fd40eceed32194ddebbd66207c6b6dede645138bc98ffa4913510cc'

GENERATED_AT = '2026-07-30T23:53:02.350774+00:00'

BLOCK_COUNT = 37

ENUMERATION_KIND_COUNT = 10

QUANTITYKINDS_REFERENCED = ['Pressure', 'SpecificEnergy', 'TemperatureDifference', 'ThermodynamicTemperature', 'Time', 'VolumeFlowRate']

UNITS_REFERENCED = ['J-PER-KiloGM', 'K', 'M3-PER-SEC', 'PA', 'SEC', 'UNITLESS']
