from dataclasses import dataclass, field
from typing import Dict, List, Optional, Set


@dataclass
class ComplexConstraintIR:
    """A SHACL constraint that can't be represented as a single typed field."""
    path_local: Optional[str]
    kind: str  # 'sparql' | 'or' | 'nested-node' | 'inverse-path' | 'forbidden' | 'other'
    comment: Optional[str]
    message: Optional[str]
    severity: Optional[str]
    raw_turtle: str


@dataclass
class PropertyShapeIR:
    """A SHACL property shape that maps to one required_field()/optional_field()."""
    path_local: str
    field_name: str
    target_class_local: Optional[str]
    datatype_local: Optional[str]
    min_count: Optional[int]
    max_count: Optional[int]
    qualified: bool
    comment: Optional[str]
    message: Optional[str]
    supplementary_notes: List[ComplexConstraintIR] = field(default_factory=list)


@dataclass
class ClassIR:
    iri: str
    local_name: str
    class_name: str
    label: Optional[str]
    comment: Optional[str]
    parent_local_names: List[str]  # parents generated in this same ontology run
    is_abstract: bool
    is_enumeration_value: bool
    bucket: str  # 'entities' | 'properties' | 'enumerationkinds'
    property_shapes: List[PropertyShapeIR] = field(default_factory=list)
    complex_constraints: List[ComplexConstraintIR] = field(default_factory=list)
    # Scaffold parents: domain core.py roots or classes from a *different* ontology
    # run (e.g. g36:Fan's parent s223:Fan) - kept separate from parent_local_names
    # since both can share a local_name with an in-run class (e.g. g36's own Fan)
    # without ambiguity.
    external_parent_local_names: List[str] = field(default_factory=list)
    # local_name of the nearest real ancestor generated by a *different* ontology
    # run, found by walking up parent_local_names/external_parent_local_names -
    # set when this class (like every g36 class) is purely a specialization that's
    # never itself an asserted RDF type (see the ontology's own annotation-rule
    # inference pattern); forces the emitted class's `_name` to that ancestor's
    # real ontology term instead of defaulting to this class's own name.
    asserted_type_local: Optional[str] = None


@dataclass
class RelationIR:
    iri: str
    local_name: str
    class_name: str
    label: Optional[str]
    comment: Optional[str]
    kind: str  # 'Relation' | 'RelationWithInverse' | 'SymmetricRelation'
    inverse_of_local: Optional[str]


@dataclass
class OntologyIR:
    classes: Dict[str, ClassIR] = field(default_factory=dict)      # keyed by local_name
    relations: Dict[str, RelationIR] = field(default_factory=dict)  # keyed by local_name
    quantitykinds_referenced: Set[str] = field(default_factory=set)
    external_relations: Set[str] = field(default_factory=set)  # available, generated elsewhere
    source_meta: dict = field(default_factory=dict)
