"""AUTO-GENERATED by semantic_objects.ingest - DO NOT EDIT.

Source ontology: /Users/lazlopaul/Desktop/HPflex/semantic_objects/src/semantic_objects/ontologies/s223/223p.ttl
Source SHA256:   47bdad8925032c84e750e46b3649d102f4e41190c8161df3c9efa3265009b0e0
See _meta.py for the generation timestamp.

Regenerate with: python -m semantic_objects.ingest.cli --ontology s223
Hand customizations belong in the sibling non-generated module, which imports from
this one - never edit this file directly, changes will be overwritten.
"""

from typing import Self
from ...core import *
from ..core import Node, EnumerationKind, ExternalReference
from . import relations
from . import enumerationkinds
from ...qudt import Unit, QuantityKind
__all__ = ['Property', 'ActuatableProperty', 'EnumerableProperty', 'EnumeratedActuatableProperty', 'ObservableProperty', 'EnumeratedObservableProperty', 'QuantifiableProperty', 'QuantifiableActuatableProperty', 'QuantifiableObservableProperty']


@semantic_object
class Property(Node):
    label = 'Property'
    comment = 'An attribute, quality, or characteristic of a feature of interest.\n\nThe `Property` class is the parent of all variations of a `Property`, which are:\n\n- `ActuatableProperty`, a subclass of `Property` that can be modified by user or machine outside of the model (typically command);\n- `ObservableProperty`, a subclass of `Property` that are observed (typically measures);\n- `EnumerableProperty`, a subclass of `Property` defined by `EnumerationKind`; and\n- `QuantifiableProperty`, a subclass of `Property` defined by numerical values.\n\nAnd their subclass combinations:\n\n- `QuantifiableActuatableProperty`,\n- `QuantifiableObservableProperty`,\n- `EnumeratedObservableProperty`, and\n- `EnumeratedActuatableProperty`.\n\nA `QuantifiableProperty` (or subclass thereof) shall always be associated with a `Unit` and a `QuantityKind`, either explicitly from the `Property`,\nor through the associated Value. If the `Unit` is defined, the SHACL reasoner (if invoked) will figure out and assert a `QuantityKind` if it is\nunambiguous.\n\nEnumerable properties shall be associated with an `EnumerationKind`. Different flavors of properties are shown in Figure 11-1.\n\n![Different flavors of Properties](figures/Figure_11-1_Flavors_of_Properties.svg)\n\nA `Property` instance that is not an instance of one of the subclasses is unconstrained with respect to its value.'
    # 8 SHACL constraint(s) not represented above - see _raw_shapes.RAW_SHAPES['Property']
    _valid_relations = [(relations.ofSubstance, enumerationkinds.Substance), (relations.hasAspect, EnumerationKind), (relations.ofMedium, enumerationkinds.Medium), (relations.hasInternalReference, Self), (relations.isInternalReferenceOf, Self), (relations.hasExternalReference, ExternalReference)]


@semantic_object
class ActuatableProperty(Property):
    label = 'Actuatable property'
    comment = 'The term "actuatable" implies that writing to the `ActuatableProperty` value will directly trigger a physical actuation by either an `Actuator` or `Equipment`.\nIn contrast, the term "observable" (see {s223:ObservableProperty}) implies that reading the `ObservableProperty` value will return the result of a physical observation.'


@semantic_object
class EnumerableProperty(Property):
    label = 'Enumerable property'
    comment = 'An `EnumerableProperty` is a `Property` with an enumerated (fixed) set of possible values.'
    # 1 SHACL constraint(s) not represented above - see _raw_shapes.RAW_SHAPES['EnumerableProperty']
    enumeration_kind: EnumerationKind = required_field(relation=relations.hasEnumerationKind, min=1, max=1, qualified=False)


@semantic_object
class EnumeratedActuatableProperty(ActuatableProperty, EnumerableProperty):
    label = 'Enumerated actuatable property'
    comment = 'An `EnumeratedActuatableProperty` is a `Property` with an enumerated (fixed) set of possible values that can be changed (actuated).'


@semantic_object
class ObservableProperty(Property):
    label = 'Observable property'
    comment = 'The term "observable" implies that reading the `ObservableProperty` value will return the result of a physical observation, usually by a `Sensor`.\nIn contrast, the term "actuatable" (see {s223:ActuatableProperty}) implies that writing to the `ActuatableProperty` value will directly trigger a physical actuation.'
    # 1 SHACL constraint(s) not represented above - see _raw_shapes.RAW_SHAPES['ObservableProperty']


@semantic_object
class EnumeratedObservableProperty(EnumerableProperty, ObservableProperty):
    label = 'Enumerated observable property'
    comment = 'An `EnumeratedObservableProperty` is a `Property` with an enumerated (fixed) set of possible values that cannot be changed (can only be observed).'


@semantic_object
class QuantifiableProperty(Property):
    label = 'Quantifiable property'
    comment = 'This class is for quantifiable values that describe an object (`System`, `Equipment`, etc.) that are typically static (`hasValue`). That is, they are neither measured nor specified in the course of operations.'
    # 6 SHACL constraint(s) not represented above - see _raw_shapes.RAW_SHAPES['QuantifiableProperty']
    _valid_relations = [(relations.hasDeadband, Self), (relations.hasThreshold, Self), (relations.hasSetpoint, Self), (relations.hasAlarmStatus, EnumerableProperty)]


@semantic_object
class QuantifiableActuatableProperty(ActuatableProperty, QuantifiableProperty):
    label = 'Quantifiable actuatable property'
    comment = 'This class is for instances of `QuantifiableProperty` for which numerical values are specified to be modifiable by a user or a machine outside of the model, like a setpoint.'


@semantic_object
class QuantifiableObservableProperty(ObservableProperty, QuantifiableProperty):
    label = 'Quantifiable observable property'
    comment = 'This class is for instances of `QuantifiableProperty` for which numerical values are observed, like a temperature reading or a voltage measure.'

