"""AUTO-GENERATED by semantic_objects.ingest - DO NOT EDIT.

Source ontology: /Users/lazlopaul/Desktop/HPflex/semantic_objects/src/semantic_objects/ontologies/s223/223p.ttl
Source SHA256:   47bdad8925032c84e750e46b3649d102f4e41190c8161df3c9efa3265009b0e0
See _meta.py for the generation timestamp.

Regenerate with: python -m semantic_objects.ingest.cli --ontology s223
Hand customizations belong in the sibling non-generated module, which imports from
this one - never edit this file directly, changes will be overwritten.
"""

from ...core import semantic_object, Predicate as _CorePredicate
from ...namespaces import S223
__all__ = ['Predicate', 'actuatedByProperty', 'actuates', 'cnx', 'composedOf', 'connected', 'connectedFrom', 'connectedThrough', 'connectedTo', 'connectsAt', 'connectsFrom', 'connectsThrough', 'connectsTo', 'contains', 'encloses', 'executes', 'hasACLineLineVoltage', 'hasACLineNeutralVoltage', 'hasAlarmStatus', 'hasAspect', 'hasBoundaryConnectionPoint', 'hasConnectionPoint', 'hasDCDifferentialVoltage', 'hasDCNegativeVoltage', 'hasDCPositiveVoltage', 'hasDCZeroVoltage', 'hasDeadband', 'hasDomain', 'hasDomainSpace', 'hasElectricalPhase', 'hasEnumerationKind', 'hasExternalReference', 'hasFreezingPoint', 'hasFrequency', 'hasInput', 'hasInternalReference', 'hasMeasurementResolution', 'hasMedium', 'hasMember', 'hasNumberOfElectricalPhases', 'hasObservationLocation', 'hasOptionalConnectionPoint', 'hasOutput', 'hasPhysicalLocation', 'hasProperty', 'hasReferenceLocation', 'hasRole', 'hasSetpoint', 'hasThermodynamicPhase', 'hasThreshold', 'hasValue', 'hasZone', 'inverseOf', 'isConnectionPointOf', 'isInternalReferenceOf', 'mapsTo', 'observes', 'ofConstituent', 'ofMedium', 'ofSubstance']

@semantic_object
class Predicate(_CorePredicate):
    _ns = S223

@semantic_object
class actuatedByProperty(Predicate):
    label = 'actuated by property'
    comment = 'A `Relation` that associates a piece of `Equipment` with the `ActuatableProperty` that it responds to. If the `Equipment`\nis an `Actuator` (a subclass of `Equipment`), `actuatedByProperty` is a required relation. An `Actuator` may also identify another piece of\n`Equipment` being actuated (see {s223:actuates}).'

@semantic_object
class actuates(Predicate):
    label = 'actuates'
    comment = 'A `Relation` that associates an `Actuator` with the `Equipment` that it actuates.'

@semantic_object
class cnx(Predicate):
    label = 'cnx'
    comment = 'A `Relation` that associates adjacent entities in a connection path, comprised of `Equipment`-`ConnectionPoint`-`Connection`-`ConnectionPoint`-`Equipment` sequences.'

@semantic_object
class composedOf(Predicate):
    label = 'composed of'
    comment = 'The relation `composedOf` is used to indicate what substances constitute a material. Allowable values are instances of `Property` that in turn identify constituents defined in `Medium-Constituent` (see {s223:Medium-Constituent}) via the relation `ofConstituent`.'

@semantic_object
class connected(Predicate):
    label = 'connected'
    comment = 'The relation `connected` indicates that two connectable things are `connected` without regard to the direction of flow.'

@semantic_object
class connectedFrom(Predicate):
    label = 'connected from'
    comment = 'The relation `connectedFrom` indicates that connectable things are `connected` with a specific direction of flow. B is `connectedFrom` A, means that the direction of flow is from A to B.  The inverse direction is indicated by `connectedTo` (see {s223:connectedTo}).'
    # inverse of s223:connectedTo

@semantic_object
class connectedThrough(Predicate):
    label = 'connected through'
    comment = 'A `Relation` that associates a `Connectable` thing with a `Connection`, without regard to the direction of flow. It is used to discover what connection links two connectable things.'

@semantic_object
class connectedTo(Predicate):
    label = 'connected to'
    comment = 'The relation `connectedTo` indicates that connectable things are `connected` with a specific direction of flow. A is `connectedTo` B, means a direction of flow from A to B.  The inverse direction is indicated by `connectedFrom` (see {s223:connectedFrom}).'
    # inverse of s223:connectedFrom

@semantic_object
class connectsAt(Predicate):
    label = 'connects at'
    comment = 'A `Relation` that associates a `Connection` with a specific `ConnectionPoint`.'
    # inverse of s223:connectsThrough

@semantic_object
class connectsFrom(Predicate):
    label = 'connects from'
    comment = 'A `Relation` that associates a `Connectable` thing with a `Connection`, with an implied direction of flow. B `connectsFrom` A indicates a flow from A to B.'

@semantic_object
class connectsThrough(Predicate):
    label = 'connects through'
    comment = 'A `Relation` that associates a `ConnectionPoint` with a `Connection`, without regard to the direction of flow.'
    # inverse of s223:connectsAt

@semantic_object
class connectsTo(Predicate):
    label = 'connects to'
    comment = 'A `Relation` that associates a `Connection` with a `Connectable` thing, with an implied direction of flow. A `connectsTo` B indicates a flow from A to B.'

@semantic_object
class contains(Predicate):
    label = 'contains'
    comment = 'A `Relation` that associates a piece of `Equipment` with its component pieces of `Equipment`, or a `PhysicalSpace` (see {s223:PhysicalSpace}) with its component `PhysicalSpace`s.'

@semantic_object
class encloses(Predicate):
    label = 'encloses'
    comment = 'A `Relation` that associates a `PhysicalSpace` with one or more `DomainSpace`s.'

@semantic_object
class executes(Predicate):
    label = 'executes'
    comment = 'A `Relation` that associates a `Controller` (see {s223:Controller}) with the `Function`s (see {s223:Function}) that it executes.'

@semantic_object
class hasACLineLineVoltage(Predicate):
    label = 'has AC line-line voltage'
    comment = 'A `Relation` that associates a `Constituent-Electricity` with an electrical voltage between two live lines.'

@semantic_object
class hasACLineNeutralVoltage(Predicate):
    label = 'has AC line-neutral voltage'
    comment = 'A `Relation` that associates an `Electricity-AC` medium with an electrical voltage between a live line and a neutral line.'

@semantic_object
class hasAlarmStatus(Predicate):
    label = 'has alarm status'
    comment = 'A `Relation` that associates an `EnumerableProperty` that describes an Alarm or Status with a `QuantifiableProperty`.'

@semantic_object
class hasAspect(Predicate):
    label = 'has aspect'
    comment = '`hasAspect` is used to establish the context of a `Property`. The value must be an instance of `EnumerationKind`. For example, if a `Property` has a temperature value of 45.3, the `hasAspect` relation is used to state what that represents, such as a temperature limit during working hours, etc. A `Property` can have any number of `hasAspect` relations as needed to establish the context.'

@semantic_object
class hasBoundaryConnectionPoint(Predicate):
    label = 'has boundary connection point'
    comment = 'The `hasBoundaryConnectionPoint` relation means the `ConnectionPoint` represents the boundary of a `System` (see {s223:System}) defined by the modeler, such as a model fragment provided by the vendor of a collection of equipment intended for integration with another model. The presence of this relation is used to indicate that such a "dangling connection point" should not generate a validation error in a non-integrated context but should generate an error in an integrated context.'

@semantic_object
class hasConnectionPoint(Predicate):
    label = 'has connection point'
    comment = 'One of two `Relation`s that associates `Connectable` thing with a `ConnectionPoint`. It is the inverse of the relation `isConnectionPointOf` (see {s223:isConnectionPointOf}).'
    # inverse of s223:isConnectionPointOf

@semantic_object
class hasDCDifferentialVoltage(Predicate):
    label = 'has DC differential voltage'
    comment = 'A `Relation` that associates an `Electricity-DC` medium with a differential voltage.'

@semantic_object
class hasDCNegativeVoltage(Predicate):
    label = 'has DC negative voltage'
    comment = 'A `Relation` that associates an `Electricity-DC` medium with a negative polarity voltage.'

@semantic_object
class hasDCPositiveVoltage(Predicate):
    label = 'has DC positive voltage'
    comment = 'A `Relation` that associates an `Electricity-DC` medium with a positive polarity voltage.'

@semantic_object
class hasDCZeroVoltage(Predicate):
    label = 'has DC zero voltage'
    comment = 'A `Relation` that associates an `Electricity-DC` medium with a zero value voltage.'

@semantic_object
class hasDeadband(Predicate):
    label = 'has deadband'
    comment = 'This relation binds a control setpoint to the `QuantifiableProperty` indicating the range of values within which a sensed variable can vary without indicating a condition has changed.'

@semantic_object
class hasDomain(Predicate):
    label = 'has domain'
    comment = 'A `Relation` that associates a `Zone` or `DomainSpace` with an `EnumerationKind-Domain` (e.g., `Domain-HVAC`, `Domain-Lighting`).'

@semantic_object
class hasDomainSpace(Predicate):
    label = 'has domain space'
    comment = 'A `Relation` that associates a `Zone` with its component `DomainSpace`s.'

@semantic_object
class hasElectricalPhase(Predicate):
    label = 'has electrical phase'
    comment = 'A `Relation` that associates a `Conductor` or `ConnectionPoint` with at most one `EnumerationKind-ElectricalPhaseIdentifier`.'

@semantic_object
class hasEnumerationKind(Predicate):
    label = 'has enumeration kind'
    comment = 'A `Relation` that associates an `EnumerableProperty` with a class of enumeration values. This is used to, for example, identify what kind of substance is transported along a `Connection` or which day of the week a setpoint is active.'

@semantic_object
class hasExternalReference(Predicate):
    label = 'has external reference'
    comment = 'A `Relation` that associates a `Property` with an external telemetry source.'

@semantic_object
class hasFreezingPoint(Predicate):
    label = 'has freezing point'
    comment = 'The relation `hasFreezingPoint` is used to associate a freezing point with a glycol solution, but could be used with other `Substance-Medium`s as appropriate.'

@semantic_object
class hasFrequency(Predicate):
    label = 'has frequency'
    comment = 'A `Relation` that associates an `Electricity-AC` with its electrical frequency.'

@semantic_object
class hasInput(Predicate):
    label = 'has input'
    comment = 'A `Relation` that associates a `Function` (see {s223:Function}) with a `Property` (see {s223:Property}) that is used as input to the `Function`.'

@semantic_object
class hasInternalReference(Predicate):
    label = 'has internal reference'
    comment = 'A `Relation` that associates a `Property` with another equivalent `Property`. For example, a `Property` that represents a `Zone`\ntemperature could have one or more `hasInternalReference` relations to another `Property` that is a temperature measurement from one room in the zone (see Figure 11-2).\n\n![Zone Internal Reference.](figures/Figure_11-2_Zone_Internal_Reference.svg)\n\nAnother use of `hasInternalReference` is to make a `Property` of a piece of equipment\nvisible as a `Property` of a piece of containing equipment.\nThis is illustrated in Figure 11-3.\n\n![Equipment Containment.](figures/Figure_11-3_Equipment_Contains_3.svg)\n\nNote that the `hasInternalReference` relation is transitive.'
    # inverse of s223:isInternalReferenceOf

@semantic_object
class hasMeasurementResolution(Predicate):
    label = 'has measurement resolution'
    comment = 'A `Relation` that associates a `Sensor` with the `QuantifiableProperty` whose value indicates the smallest recognizable change in engineering units that the `Sensor` is able to measure.'

@semantic_object
class hasMedium(Predicate):
    label = 'has medium'
    comment = 'The relation `hasMedium` is used to indicate what medium is flowing through the connection (e.g., air, water, electricity). The possible values are defined in `Substance-Medium` (see {s223:Substance-Medium}).'

@semantic_object
class hasMember(Predicate):
    label = 'has member'
    comment = 'A `Relation` that associates a `System` with its component `Equipment` and/or `System`s.'

@semantic_object
class hasNumberOfElectricalPhases(Predicate):
    label = 'has number of electrical phases'
    comment = 'A `Relation` that associates an AC electricity `Substance-Medium` with its number of electrical phases.'

@semantic_object
class hasObservationLocation(Predicate):
    label = 'has observation location'
    comment = 'A `Relation` that associates a `Sensor` with the topological location where it is observing a `Property` (see {s223:observes}). The observation location shall be a `Connectable` (see {s223:Connectable}), `Connection` (see {s223:Connection}), or `ConnectionPoint` (see {s223:ConnectionPoint}).'

@semantic_object
class hasOptionalConnectionPoint(Predicate):
    label = 'has optional connection point'
    comment = 'The `hasOptionalConnectionPoint` relation means that the `ConnectionPoint` is optional and is not required to be connected. The presence of this relation is used to indicate that such a "dangling connection point" should not generate a validation error in an integrated or non-integrated context.'

@semantic_object
class hasOutput(Predicate):
    label = 'has output'
    comment = 'A `Relation` that associates a `Function` (see {s223:Function}) with a `Property` (see {s223:Property}) that is calculated by the `Function`.'

@semantic_object
class hasPhysicalLocation(Predicate):
    label = 'has physical location'
    comment = 'A `Relation` that associates a piece of `Equipment` with its physical location (i.e., in a `PhysicalSpace`). The physical location of a piece of `Equipment` is not necessarily the same as the location affected by the operation of the `Equipment`. For example, an air handler may physically be located on the roof, but its effect is to provide conditioned air to a `Zone` or `DomainSpace` within the building. By following the path of connections, it can be determined what other equipment or spaces are possibly impacted by the `Equipment`.'

@semantic_object
class hasProperty(Predicate):
    label = 'has property'
    comment = 'A `Relation` that associates a `Concept` with a `Property`.'

@semantic_object
class hasReferenceLocation(Predicate):
    label = 'has reference location'
    comment = 'A `Relation` that associates  a differential sensor with the topological location of the baseline (reference) `Property` (see {s223:observes}).'

@semantic_object
class hasRole(Predicate):
    label = 'has role'
    comment = 'A `Relation` that associates a role with of a piece of `Equipment`, a `Connection`, `ConnectionPoint`, or `System` within a building (e.g., a heating coil might be associated with `Role-Heating`). Possible values are defined in `EnumerationKind-Role` (see {s223:EnumerationKind-Role}).'

@semantic_object
class hasSetpoint(Predicate):
    label = 'has setpoint'
    comment = 'A `Relation` that associates a control setpoint with the `QuantifiableProperty` indicating the desired value which the control process is trying to maintain.'

@semantic_object
class hasThermodynamicPhase(Predicate):
    label = 'has thermodynamic phase'
    comment = 'A `Relation` that associates a Medium with its thermodynamic phases.'

@semantic_object
class hasThreshold(Predicate):
    label = 'has threshold'
    comment = 'A `Relation` that associates a threshold with the `QuantifiableProperty` indicating a specific value at which an action may be taken, distinguished from an offset or a range.'

@semantic_object
class hasValue(Predicate):
    label = 'has value'
    comment = 'A `Relation` that associates something with a fixed value, as opposed to a computed, measured, or externally derived value.'

@semantic_object
class hasZone(Predicate):
    label = 'has zone'
    comment = 'A `Relation` that associates a `Zone` with component `Zone`s.'

@semantic_object
class inverseOf(Predicate):
    label = 'inverse of'
    comment = 'A `Relation` that associates `Relation`s that are inverses of one another, such as `connectedTo` and `connectedFrom`.'

@semantic_object
class isConnectionPointOf(Predicate):
    label = 'is connection point of'
    comment = 'One of two `Relation`s that associates a `ConnectionPoint` with a `Connectable` thing. It is the inverse of the relation `hasConnectionPoint` (see {s223:hasConnectionPoint}).'
    # inverse of s223:hasConnectionPoint

@semantic_object
class isInternalReferenceOf(Predicate):
    label = 'is internal reference of'
    comment = 'The inverse of the relation `hasInternalReference` (see {s223:hasInternalReference}).'
    # inverse of s223:hasInternalReference

@semantic_object
class mapsTo(Predicate):
    label = 'maps to'
    comment = 'A `Relation` that associates a `ConnectionPoint` of a `Connectable` with a corresponding `ConnectionPoint` of the one containing it. The associated `ConnectionPoint`s shall have a compatible medium (see {s223:Substance-Medium}).'

@semantic_object
class observes(Predicate):
    label = 'observes'
    comment = 'A `Relation` that associates a `Sensor` with one `ObservableProperty` (see {s223:ObservableProperty})\nwhich is used by the sensor to generate a measurement value (e.g., a temperature) or a simple observation of a stimulus\ncausing a reaction (e.g., a current binary switch that closes a dry contact when a fan is powered on).'

@semantic_object
class ofConstituent(Predicate):
    label = 'of constituent'
    comment = 'A `Relation` that associates a `Property` that characterizes a `Medium-Mix` with one of the constituents of that mix (e.g., `Fluid-Water` `composedOf` `Property` `ofConstituent` `Constituent-H2O`).'

@semantic_object
class ofMedium(Predicate):
    label = 'of medium'
    comment = 'A `Relation` that associates a `Property` with the specific Medium it describes. A `Property` corresponding to the temperature of a medium would be associated with this medium using the relation `ofMedium`.'

@semantic_object
class ofSubstance(Predicate):
    label = 'of substance'
    comment = 'A `Relation` that associates a `Property` being observed by a `Sensor` with the `EnumerationKind-Substance` it characterizes within a specific `Substance-Medium`. For example, to denote the concentration of a `EnumerationKind-Substance` in a `Substance-Medium`, `ofSubstance` is used. Typically, there is also an `ofMedium` relation between the observed `Property` and the `Substance-Medium` (see Figures 10-9 and 10-10). For example, to represent the concentration of CO2 in air, we use `ofSubstance` to relate to CO2 and `ofMedium` to relate to air. The term `ofSubstance` is broad enough to include situations where a sensor is used to detect constituents that should not be present in a medium, such as ammonia in air. Therefore, `ofSubstance` is used to indicate the substance of interest, while `ofConstituent` would indicate a constituent that is normally present in the composition of the mix.'
