"""AUTO-GENERATED by semantic_objects.ingest - DO NOT EDIT.

Source ontology: /Users/lazlopaul/Desktop/223p/experiments/semantic_objects/.claude/worktrees/cxf-ingestion/src/semantic_objects/ontologies/cxf/Buildings/Controls/OBC/ASHRAE/G36
Source file count SHA256: 381dac3f5fd40eceed32194ddebbd66207c6b6dede645138bc98ffa4913510cc

Regenerate with: python -m semantic_objects.ingest.cli --ontology cxf
Hand customizations belong in the sibling non-generated module, which imports
from this one - never edit this file directly, changes will be overwritten.
"""

from semantic_objects.core import semantic_object
from semantic_objects.cxf.core import Block
from semantic_objects.cxf.core import RealInputPort
from semantic_objects.cxf.core import RealOutputPort
from semantic_objects.cxf.core import RealParameter
from semantic_objects.cxf.core import SubBlock
from semantic_objects.cxf.fields import real_input_field, real_output_field, real_parameter_field, subblock_field
from semantic_objects.qudt import quantitykinds
from semantic_objects.qudt import units

__all__ = ['ControlLoops']


@semantic_object
class ControlLoops(Block):
    _name = 'Buildings.Controls.OBC.ASHRAE.G36.ThermalZones.ControlLoops'
    comment = 'info=<html>\n<p>\nThis block outputs the heating and cooling control loop signal. The implementation\nis according to the ASHRAE Guideline 36, Section 5.3.4.\n</p>\n<ol>\n<li>\nTwo separate control loops, the cooling loop and the heating loop, shall operate to\nmaintain space temperature at set point.\n<ul>\n<li>\nThe heating loop shall be enabled whenever the space temperature <code>TZon</code>\nis below the current zone heating setpoint temperature <code>THeaSet</code> and\ndisabled when space temperature is above the current zone heating setpoint temperature\nand the loop output is zero for 30 seconds. The loop may remain active at all times\nif provisions are made to minimize integral windup.\n</li>\n<li>\nThe cooling loop shall be enabled whenever the space temperature <code>TZon</code>\nis above the current zone cooling setpoint temperature <code>TCooSet</code> and\ndisabled when space temperature is below the current zone cooling setpoint temperature\nand the loop output is zero for 30 seconds. The loop may remain active at all times\nif provisions are made to minimize integral windup.\n</li>\n</ul>\n</li>\n<li>\nThe cooling loop shall maintain the space temperature at the cooling setpoint. The\noutput of the loop shall be a software point ranging from 0% (no cooling) to 100%\n(full cooling).\n</li>\n<li>\nThe heating loop shall maintain the space temperature at the heating setpoint. The\noutput of the loop shall be a software point ranging from 0% (no heating) to 100%\n(full heating).\n</li>\n<li>\nLoops shall use proportional plus integral logic or other technology with similar\nperformance. Proportional-only control is not acceptable, although the integral\ngain shall be small relative to the proportional gain. P and I gains shall be adjustable\nby the operator.\n</li>\n</ol>\n</html>,revisions=<html>\n<ul>\n<li>\nAugust 1, 2020, by Jianjun Hu:<br/>\nFirst implementation.\n</li>\n</ul>\n</html>'
    TCooSet: RealInputPort = real_input_field(qk=quantitykinds.ThermodynamicTemperature, unit=units.K, description='Zone cooling setpoint')
    THeaSet: RealInputPort = real_input_field(qk=quantitykinds.ThermodynamicTemperature, unit=units.K, description='Zone heating setpoint')
    TZon: RealInputPort = real_input_field(qk=quantitykinds.ThermodynamicTemperature, unit=units.K, description='Measured zone temperature')
    yCoo: RealOutputPort = real_output_field(unit=units.UNITLESS, description='Cooling control signal')
    yHea: RealOutputPort = real_output_field(unit=units.UNITLESS, description='Heating control signal')
    dTHys: RealParameter = real_parameter_field(default=0.25, unit=units.K, description='Delta between the temperature hysteresis high and low limit')
    kCooCon: RealParameter = real_parameter_field(default=0.1, description='Gain of controller for cooling control loop')
    kHeaCon: RealParameter = real_parameter_field(default=0.1, description='Gain of controller for heating control loop')
    looHys: RealParameter = real_parameter_field(default=0.01, unit=units.UNITLESS, description='Threshold value to check if the controller output is near zero')
    TiCooCon: RealParameter = real_parameter_field(default=900, unit=units.SEC, description='Time constant of integrator block for cooling control loop')
    TiHeaCon: RealParameter = real_parameter_field(default=900, unit=units.SEC, description='Time constant of integrator block for heating control loop')
    timChe: RealParameter = real_parameter_field(default=30, unit=units.SEC, description='Threshold time to check the zone temperature status')
    colZon: SubBlock = subblock_field(description='[external type: Buildings.Controls.OBC.CDL.Logical.Not] Check if the zone temperature is lower than the cooling setpoint')
    conCoo: SubBlock = subblock_field(description='[external type: Buildings.Controls.OBC.CDL.Reals.PIDWithReset] Cooling controller')
    conHea: SubBlock = subblock_field(description='[external type: Buildings.Controls.OBC.CDL.Reals.PIDWithReset] Heating controller')
    cooConSig: SubBlock = subblock_field(description='[external type: Buildings.Controls.OBC.CDL.Reals.Multiply] Cooling control loop signal')
    disCoo: SubBlock = subblock_field(description='[external type: Buildings.Controls.OBC.CDL.Logical.TrueDelay] Check if the controller output has been near zero for a threshold time')
    disCooCon: SubBlock = subblock_field(description='[external type: Buildings.Controls.OBC.CDL.Logical.And] Check if disable cooling control loop')
    disHea: SubBlock = subblock_field(description='[external type: Buildings.Controls.OBC.CDL.Logical.TrueDelay] Check if the controller output has been near zero for a threshold time')
    disHeaCon: SubBlock = subblock_field(description='[external type: Buildings.Controls.OBC.CDL.Logical.And] Check if disable heating control loop')
    enaCooLoo: SubBlock = subblock_field(description='[external type: Buildings.Controls.OBC.CDL.Reals.Less] Check if cooling control loop should be enabled')
    enaHeaLoo: SubBlock = subblock_field(description='[external type: Buildings.Controls.OBC.CDL.Reals.Less] Check if heating control loop should be enabled')
    heaConSig: SubBlock = subblock_field(description='[external type: Buildings.Controls.OBC.CDL.Reals.Multiply] Heating control loop signal')
    holZon: SubBlock = subblock_field(description='[external type: Buildings.Controls.OBC.CDL.Logical.Not] Check if the zone temperature is higher than the heating setpoint')
    zerCon: SubBlock = subblock_field(description='[external type: Buildings.Controls.OBC.CDL.Reals.LessThreshold] Check if the controller output is near zero')
    zerCon1: SubBlock = subblock_field(description='[external type: Buildings.Controls.OBC.CDL.Reals.LessThreshold] Check if the controller output is near zero')
    zerCoo: SubBlock = subblock_field(description='[external type: Buildings.Controls.OBC.CDL.Conversions.BooleanToReal] Output zero control signal when the cooling loop should be disabled')
    zerHea: SubBlock = subblock_field(description='[external type: Buildings.Controls.OBC.CDL.Conversions.BooleanToReal] Output zero control signal when the heating loop should be disabled')
