"""AUTO-GENERATED by semantic_objects.ingest - DO NOT EDIT.

Source ontology: /Users/lazlopaul/Desktop/223p/experiments/semantic_objects/.claude/worktrees/cxf-ingestion/src/semantic_objects/ontologies/cxf/Buildings/Controls/OBC/ASHRAE/G36
Source file count SHA256: 381dac3f5fd40eceed32194ddebbd66207c6b6dede645138bc98ffa4913510cc

Regenerate with: python -m semantic_objects.ingest.cli --ontology cxf
Hand customizations belong in the sibling non-generated module, which imports
from this one - never edit this file directly, changes will be overwritten.
"""

from semantic_objects.core import semantic_object
from semantic_objects.cxf.core import Block
from semantic_objects.cxf.core import IntegerOutputPort
from semantic_objects.cxf.core import RealInputPort
from semantic_objects.cxf.core import RealParameter
from semantic_objects.cxf.core import SubBlock
from semantic_objects.cxf.fields import integer_output_field, real_input_field, real_parameter_field, subblock_field
from semantic_objects.qudt import units

__all__ = ['ZoneStates']


@semantic_object
class ZoneStates(Block):
    _name = 'Buildings.Controls.OBC.ASHRAE.G36.ThermalZones.ZoneStates'
    comment = 'info=<html>\n<p>\nBlock that outputs the zone state. It first checks if the zone is in heating state;\nif not, it checks if the zone is in cooling state; otherwise it is in deadband state.\n</p>\n<p>\nThese states are defined in\n<a href=\\modelica://Buildings.Controls.OBC.ASHRAE.G36.Types.ZoneStates\\>\nBuildings.Controls.OBC.ASHRAE.G36.Types.ZoneStates</a>.\n</p>\n<p>\nThe logic of the block is as follows.\n</p>\n<ol>\n<li>\nThe zone state is heating when both of the following two conditions are satisfied:\n(i) The heating control signal satisfies <code>uHea &gt; uHigh</code>, where\n<code>uHigh</code> is a parameter,\nand (ii) the following condition is satisfied <code>uHea - uCoo > uLow</code>,\nwhere <code>uCoo</code> is the cooling control signal and <code>uLow</code> is a parameter.\nThe second condition is\nused to avoid errors when <code>uHea > 0</code> and <code>uCoo > 0</code> at the same time.\n</li>\n<li>\nThe zone state is cooling when the zone state is not heating and the cooling control signal satisfies\n<code>uCoo > uHigh</code>, where <code>uHigh</code> is a parameter.\nIf <code>uCoo &lt; uLow</code>, then the zone state is not cooling.\n</li>\n<li>\nThe zone state is deadband when it is neither in heating state nor in cooling state.\n</li>\n</ol>\n</html>,revisions=<html>\n<ul>\n<li>\nMarch 13, 2020, by Jianjun Hu:<br/>\nReplaced <code>multiSum</code> block with two addition blocks to avoid vector related implementation.<br/>\nThis is for <a href=\\https://github.com/lbl-srg/modelica-buildings/issues/1709\\>#1709</a>.\n</li>\n<li>\nSeptember 11, 2019, by Kun Zhang:<br/>\nImproved the implementation to avoid issues when heating and cooling controls occur at the same time.\n</li>\n<li>\nOctober 24, 2018, by David Blum:<br/>\nFirst implementation.\n</li>\n</ul>\n</html>'
    uCoo: RealInputPort = real_input_field(description='Cooling control signal')
    uHea: RealInputPort = real_input_field(description='Heating control signal')
    yZonSta: IntegerOutputPort = integer_output_field(description='Zone state')
    uHigh: RealParameter = real_parameter_field(default=0.05, unit=units.UNITLESS, description='Hysteresis parameter uHigh for heating and cooling control signals to avoid chattering')
    uLow: RealParameter = real_parameter_field(default=0.01, unit=units.UNITLESS, description='Hysteresis parameter uLow for heating and cooling control signals to avoid chattering')
    addInt: SubBlock = subblock_field(description='[external type: Buildings.Controls.OBC.CDL.Integers.Add] Add two integer inputs')
    addInt1: SubBlock = subblock_field(description='[external type: Buildings.Controls.OBC.CDL.Integers.Add] Add two integer inputs')
    booToIntCoo: SubBlock = subblock_field(description='[external type: Buildings.Controls.OBC.CDL.Conversions.BooleanToInteger] Convert Boolean to Integer number')
    booToIntDea: SubBlock = subblock_field(description='[external type: Buildings.Controls.OBC.CDL.Conversions.BooleanToInteger] Convert Boolean to Integer number')
    booToIntHea: SubBlock = subblock_field(description='[external type: Buildings.Controls.OBC.CDL.Conversions.BooleanToInteger] Convert Boolean to Integer number')
    hysU: SubBlock = subblock_field(description='[external type: Buildings.Controls.OBC.CDL.Reals.Hysteresis] Check if heating control signal is bigger than cooling control signal')
    hysUCoo: SubBlock = subblock_field(description='[external type: Buildings.Controls.OBC.CDL.Reals.Hysteresis] Check if it is in cooling state')
    hysUHea: SubBlock = subblock_field(description='[external type: Buildings.Controls.OBC.CDL.Reals.Hysteresis] Check if it is in heating state')
    isCoo: SubBlock = subblock_field(description='[external type: Buildings.Controls.OBC.CDL.Logical.And] In cooling state if both inputs are true')
    isDea: SubBlock = subblock_field(description='[external type: Buildings.Controls.OBC.CDL.Logical.Nor] In deadband state')
    isHea: SubBlock = subblock_field(description='[external type: Buildings.Controls.OBC.CDL.Logical.And] In heating state if both conditions are true')
    notHea: SubBlock = subblock_field(description='[external type: Buildings.Controls.OBC.CDL.Logical.Not] Not in heating state')
    uHeaMinUCoo: SubBlock = subblock_field(description='[external type: Buildings.Controls.OBC.CDL.Reals.Subtract] Difference between uHea and uCoo')
