"""AUTO-GENERATED by semantic_objects.ingest - DO NOT EDIT.

Source ontology: /Users/lazlopaul/Desktop/223p/experiments/semantic_objects/src/semantic_objects/ontologies/s223/223p.ttl
Source SHA256:   47bdad8925032c84e750e46b3649d102f4e41190c8161df3c9efa3265009b0e0
See _meta.py for the generation timestamp.

Regenerate with: python -m semantic_objects.ingest.cli --ontology g36
Hand customizations belong in the sibling non-generated module, which imports from
this one - never edit this file directly, changes will be overwritten.
"""


SOURCE_FILE = '/Users/lazlopaul/Desktop/223p/experiments/semantic_objects/src/semantic_objects/ontologies/s223/223p.ttl'

SOURCE_SHA256 = '47bdad8925032c84e750e46b3649d102f4e41190c8161df3c9efa3265009b0e0'

GENERATED_AT = '2026-07-31T20:28:51.331100+00:00'

CLASS_COUNT = 11

RELATION_COUNT = 0

QUANTITYKINDS_REFERENCED = ['AbsoluteHumidity',
 'CorrelatedColorTemperature',
 'DimensionlessRatio',
 'Duv',
 'ElectricCurrent',
 'Frequency',
 'GaugePressure',
 'Illuminance',
 'NumberOfElectricalPhases',
 'Population',
 'Pressure',
 'RelativeHumidity',
 'Temperature',
 'Unknown',
 'Voltage',
 'VolumeFraction']


# Shapes that could not be resolved into a field or _valid_relations entry

# (out-of-scope relation namespace, or a forward/external type reference).

UNRESOLVED_NOTES = {}
