"""AUTO-GENERATED by semantic_objects.ingest - DO NOT EDIT.

Source ontology: /Users/lazlopaul/Desktop/223p/experiments/semantic_objects/src/semantic_objects/ontologies/s223/223p.ttl
Source SHA256:   47bdad8925032c84e750e46b3649d102f4e41190c8161df3c9efa3265009b0e0
See _meta.py for the generation timestamp.

Regenerate with: python -m semantic_objects.ingest.cli --ontology g36
Hand customizations belong in the sibling non-generated module, which imports from
this one - never edit this file directly, changes will be overwritten.
"""


# Complex SHACL constraints (sh:sparql, sh:or, inverse paths, forbidden properties)
# and supplementary notes on qualified fields, keyed by generated Python class name.
# Preserved for fidelity - not enforced by the framework. See docs/exact_values_generalization.md
# and the ingestion plan for how to hand-implement any of these as real validators.

RAW_SHAPES = {'ElectricHeatingCoil': [{'comment': 'Additional constraints on the qualified value beyond its '
                                     'class (medium, sub-shape, etc.) - see raw_turtle.',
                          'field_name': 'quantifiable_actuatable_property',
                          'kind': 'nested-node',
                          'message': 'g36: An electric heating coil shall have at least one analog '
                                     'heating command property using a relation hasProperty.',
                          'path': 'hasProperty',
                          'raw_turtle': '@prefix sh: <http://www.w3.org/ns/shacl#> .\n'
                                        '@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .\n'
                                        '\n'
                                        '[] sh:class '
                                        '<http://data.ashrae.org/standard223#QuantifiableActuatableProperty> '
                                        ';\n'
                                        '    sh:node [ sh:property [ sh:hasValue '
                                        '<http://qudt.org/vocab/quantitykind/DimensionlessRatio> '
                                        ';\n'
                                        '                    sh:maxCount 1 ;\n'
                                        '                    sh:minCount 1 ;\n'
                                        '                    sh:path '
                                        '<http://qudt.org/schema/qudt/hasQuantityKind> ] ] .\n'
                                        '\n'}],
 'Fan': [{'comment': 'Additional constraints on the qualified value beyond its class (medium, '
                     'sub-shape, etc.) - see raw_turtle.',
          'field_name': 'enumerated_actuatable_property',
          'kind': 'nested-node',
          'message': 'g36: A Fan shall have at least one Start/Stop command using the relation '
                     'hasProperty.',
          'path': 'hasProperty',
          'raw_turtle': '@prefix sh: <http://www.w3.org/ns/shacl#> .\n'
                        '@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .\n'
                        '\n'
                        '[] sh:class '
                        '<http://data.ashrae.org/standard223#EnumeratedActuatableProperty> ;\n'
                        '    sh:node [ sh:property [ sh:class '
                        '<http://data.ashrae.org/standard223#Binary-OnOff> ;\n'
                        '                    sh:maxCount 1 ;\n'
                        '                    sh:minCount 1 ;\n'
                        '                    sh:path '
                        '<http://data.ashrae.org/standard223#hasEnumerationKind> ] ] .\n'
                        '\n'}],
 'FanWithVFD': [{'comment': 'Additional constraints on the qualified value beyond its class '
                            '(medium, sub-shape, etc.) - see raw_turtle.',
                 'field_name': 'quantifiable_actuatable_property',
                 'kind': 'nested-node',
                 'message': 'g36: A fan with VFD shall have at least one fan speed command using '
                            'the relation hasProperty.',
                 'path': 'hasProperty',
                 'raw_turtle': '@prefix sh: <http://www.w3.org/ns/shacl#> .\n'
                               '@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .\n'
                               '\n'
                               '[] sh:class '
                               '<http://data.ashrae.org/standard223#QuantifiableActuatableProperty> '
                               ';\n'
                               '    sh:node [ sh:property [ sh:hasValue '
                               '<http://qudt.org/vocab/quantitykind/DimensionlessRatio> ;\n'
                               '                    sh:maxCount 1 ;\n'
                               '                    sh:minCount 1 ;\n'
                               '                    sh:path '
                               '<http://qudt.org/schema/qudt/hasQuantityKind> ] ] .\n'
                               '\n'}],
 'TwoPositionDamper': [{'comment': 'Additional constraints on the qualified value beyond its class '
                                   '(medium, sub-shape, etc.) - see raw_turtle.',
                        'field_name': 'enumerated_actuatable_property',
                        'kind': 'nested-node',
                        'message': 'g36: A Two Position Damper shall have at least one '
                                   'open-and-close damper command property using the relation '
                                   'hasProperty.',
                        'path': 'hasProperty',
                        'raw_turtle': '@prefix sh: <http://www.w3.org/ns/shacl#> .\n'
                                      '@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .\n'
                                      '\n'
                                      '[] sh:class '
                                      '<http://data.ashrae.org/standard223#EnumeratedActuatableProperty> '
                                      ';\n'
                                      '    sh:node [ sh:property [ sh:hasValue '
                                      '<http://data.ashrae.org/standard223#Binary-Position> ;\n'
                                      '                    sh:maxCount 1 ;\n'
                                      '                    sh:minCount 1 ;\n'
                                      '                    sh:path '
                                      '<http://data.ashrae.org/standard223#hasAspect> ],\n'
                                      '                [ sh:class '
                                      '<http://data.ashrae.org/standard223#EnumerationKind-Binary> '
                                      ';\n'
                                      '                    sh:maxCount 1 ;\n'
                                      '                    sh:minCount 1 ;\n'
                                      '                    sh:path '
                                      '<http://data.ashrae.org/standard223#hasEnumerationKind> ] ] '
                                      '.\n'
                                      '\n'}],
 'Zone': [{'comment': 'Additional constraints on the qualified value beyond its class (medium, '
                      'sub-shape, etc.) - see raw_turtle.',
           'field_name': 'quantifiable_observable_property',
           'kind': 'nested-node',
           'message': 'g36: A Zone shall have a zone temperature setpoint adjustment property '
                      'using the relation hasProperty, if applicable.',
           'path': 'hasProperty',
           'raw_turtle': '@prefix sh: <http://www.w3.org/ns/shacl#> .\n'
                         '@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .\n'
                         '\n'
                         '[] sh:class '
                         '<http://data.ashrae.org/standard223#QuantifiableObservableProperty> ;\n'
                         '    sh:node [ sh:property [ sh:hasValue '
                         '<http://qudt.org/vocab/quantitykind/Temperature> ;\n'
                         '                    sh:maxCount 1 ;\n'
                         '                    sh:minCount 1 ;\n'
                         '                    sh:path '
                         '<http://qudt.org/schema/qudt/hasQuantityKind> ],\n'
                         '                [ sh:hasValue '
                         '<http://data.ashrae.org/standard223#Aspect-Delta> ;\n'
                         '                    sh:maxCount 1 ;\n'
                         '                    sh:minCount 1 ;\n'
                         '                    sh:path '
                         '<http://data.ashrae.org/standard223#hasAspect> ] ] .\n'
                         '\n'},
          {'comment': 'Additional constraints on the qualified value beyond its class (medium, '
                      'sub-shape, etc.) - see raw_turtle.',
           'field_name': 'quantifiable_observable_property_2',
           'kind': 'nested-node',
           'message': 'g36: A Zone shall have at least a zone CO2 concentration property using the '
                      'relation hasProperty, if applicable control is used.',
           'path': 'hasProperty',
           'raw_turtle': '@prefix sh: <http://www.w3.org/ns/shacl#> .\n'
                         '@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .\n'
                         '\n'
                         '[] sh:class '
                         '<http://data.ashrae.org/standard223#QuantifiableObservableProperty> ;\n'
                         '    sh:node [ sh:property [ sh:hasValue '
                         '<http://qudt.org/vocab/quantitykind/DimensionlessRatio> ;\n'
                         '                    sh:maxCount 1 ;\n'
                         '                    sh:minCount 1 ;\n'
                         '                    sh:path '
                         '<http://qudt.org/schema/qudt/hasQuantityKind> ],\n'
                         '                [ sh:hasValue '
                         '<http://data.ashrae.org/standard223#Constituent-CO2> ;\n'
                         '                    sh:maxCount 1 ;\n'
                         '                    sh:minCount 1 ;\n'
                         '                    sh:path '
                         '<http://data.ashrae.org/standard223#ofConstituent> ] ] .\n'
                         '\n'},
          {'comment': 'Additional constraints on the qualified value beyond its class (medium, '
                      'sub-shape, etc.) - see raw_turtle.',
           'field_name': 'enumerated_observable_property',
           'kind': 'nested-node',
           'message': 'g36: A Zone shall have at least one binary zone occupancy property using '
                      'the relation hasProperty',
           'path': 'hasProperty',
           'raw_turtle': '@prefix sh: <http://www.w3.org/ns/shacl#> .\n'
                         '@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .\n'
                         '\n'
                         '[] sh:class '
                         '<http://data.ashrae.org/standard223#EnumeratedObservableProperty> ;\n'
                         '    sh:node [ sh:property [ sh:class '
                         '<http://data.ashrae.org/standard223#EnumerationKind-Occupancy> ;\n'
                         '                    sh:maxCount 1 ;\n'
                         '                    sh:minCount 1 ;\n'
                         '                    sh:path '
                         '<http://data.ashrae.org/standard223#hasEnumerationKind> ] ] .\n'
                         '\n'},
          {'comment': 'Additional constraints on the qualified value beyond its class (medium, '
                      'sub-shape, etc.) - see raw_turtle.',
           'field_name': 'enumerated_observable_property_2',
           'kind': 'nested-node',
           'message': 'g36: A Zone shall have at least one window switch on-off property using the '
                      'relation hasProperty.',
           'path': 'hasProperty',
           'raw_turtle': '@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .\n'
                         '@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .\n'
                         '@prefix sh: <http://www.w3.org/ns/shacl#> .\n'
                         '@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .\n'
                         '\n'
                         '[] sh:class '
                         '<http://data.ashrae.org/standard223#EnumeratedObservableProperty> ;\n'
                         '    sh:node [ sh:property [ sh:class '
                         '<http://data.ashrae.org/standard223#Binary-OnOff> ;\n'
                         '                    sh:maxCount 1 ;\n'
                         '                    sh:minCount 1 ;\n'
                         '                    sh:path '
                         '<http://data.ashrae.org/standard223#hasEnumerationKind> ],\n'
                         '                [ rdfs:comment "Property shall be measured at a '
                         'window."^^xsd:string ;\n'
                         '                    sh:class <http://data.ashrae.org/standard223#Window> '
                         ';\n'
                         '                    sh:path [ sh:alternativePath ( ( [ sh:inversePath '
                         '<http://data.ashrae.org/standard223#observes> ] '
                         '<http://data.ashrae.org/standard223#hasObservationLocation> ) [ '
                         'sh:inversePath <http://data.ashrae.org/standard223#hasProperty> ] ) ] ] '
                         '] .\n'
                         '\n'},
          {'comment': 'A Zone shall have at least one Domain-HVAC using the relation hasDomain. ',
           'field_name': None,
           'kind': 'other',
           'message': 'g36: A Zone shall have at least one Domain-HVAC using the relation '
                      'hasDomain. ',
           'path': 'hasDomain',
           'raw_turtle': '@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .\n'
                         '@prefix sh: <http://www.w3.org/ns/shacl#> .\n'
                         '@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .\n'
                         '\n'
                         '[] rdfs:comment "A Zone shall have at least one Domain-HVAC using the '
                         'relation hasDomain. "^^xsd:string ;\n'
                         '    sh:hasValue <http://data.ashrae.org/standard223#Domain-HVAC> ;\n'
                         '    sh:message "g36: A Zone shall have at least one Domain-HVAC using '
                         'the relation hasDomain. "^^xsd:string ;\n'
                         '    sh:minCount 1 ;\n'
                         '    sh:path <http://data.ashrae.org/standard223#hasDomain> .\n'
                         '\n'}],
 'ZoneGroup': [{'comment': 'A ZoneGroup shall have the Domain HVAC using the relation hasDomain.',
                'field_name': None,
                'kind': 'other',
                'message': 'g36: A ZoneGroup shall have the Domain HVAC using the relation '
                           'hasDomain.',
                'path': 'hasDomain',
                'raw_turtle': '@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .\n'
                              '@prefix sh: <http://www.w3.org/ns/shacl#> .\n'
                              '@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .\n'
                              '\n'
                              '[] rdfs:comment "A ZoneGroup shall have the Domain HVAC using the '
                              'relation hasDomain."^^xsd:string ;\n'
                              '    sh:hasValue <http://data.ashrae.org/standard223#Domain-HVAC> ;\n'
                              '    sh:message "g36: A ZoneGroup shall have the Domain HVAC using '
                              'the relation hasDomain."^^xsd:string ;\n'
                              '    sh:minCount 1 ;\n'
                              '    sh:path <http://data.ashrae.org/standard223#hasDomain> .\n'
                              '\n'}]}
