"""AUTO-GENERATED by semantic_objects.ingest - DO NOT EDIT.

Source ontology: /Users/lazlopaul/Desktop/223p/experiments/semantic_objects/.claude/worktrees/cxf-ingestion/src/semantic_objects/ontologies/cxf/Buildings/Controls/OBC/ASHRAE/G36
Source file count SHA256: 381dac3f5fd40eceed32194ddebbd66207c6b6dede645138bc98ffa4913510cc

Regenerate with: python -m semantic_objects.ingest.cli --ontology cxf
Hand customizations belong in the sibling non-generated module, which imports
from this one - never edit this file directly, changes will be overwritten.
"""

from semantic_objects.core import semantic_object
from semantic_objects.cxf.core import Block
from semantic_objects.cxf.core import BooleanInputPort
from semantic_objects.cxf.core import IntegerInputPort
from semantic_objects.cxf.core import RealInputPort
from semantic_objects.cxf.core import RealOutputPort
from semantic_objects.cxf.core import SubBlock
from semantic_objects.cxf.fields import boolean_input_field, integer_input_field, real_input_field, real_output_field, subblock_field
from semantic_objects.qudt import units

__all__ = ['Overrides']


@semantic_object
class Overrides(Block):
    _name = 'Buildings.Controls.OBC.ASHRAE.G36.TerminalUnits.Reheat.Subsequences.Overrides'
    comment = 'info=<html>\n<p>\nThis block considers the overrides to the setpoints for terminal unit with reheat.\nThe implementation is according to the Section 5.6.7 of ASHRAE Guideline 36,\nMay 2020.\n</p>\n<p>\nProvide software switches that interlock to a system-level point to:\n</p>\n<ol>\n<li>\nwhen <code>oveDamPos</code> equals to 1, force the damper to full closed by setting\n<code>yDam</code> to 0,\n</li>\n<li>\nwhen <code>oveDamPos</code> equals to 2, force the damper to full open by setting\n<code>yDam</code> to 1.\n</li>\n<li>\nwhen <code>uHeaOff</code> equals to <code>true</code>, force the heating valve to\nfull closed by setting <code>yVal</code> to 0.\n</li>\n</ol>\n</html>,revisions=<html>\n<ul>\n<li>\nAugust 1, 2020, by Jianjun Hu:<br/>\nFirst implementation.\n</li>\n</ul>\n</html>'
    oveDamPos: IntegerInputPort = integer_input_field(description='Index of overriding damper position, 1: set to close; 2: set to open')
    uDam: RealInputPort = real_input_field(unit=units.UNITLESS, description='Damper commanded position')
    uHeaOff: BooleanInputPort = boolean_input_field(description='Override heating valve position, true: close heating valve')
    uVal: RealInputPort = real_input_field(unit=units.UNITLESS, description='Heating valve commanded position')
    yDam: RealOutputPort = real_output_field(unit=units.UNITLESS, description='Damper commanded position, after considering override')
    yVal: RealOutputPort = real_output_field(unit=units.UNITLESS, description='Heating valve commanded position, after considering override')
    add3: SubBlock = subblock_field(description='[external type: Buildings.Controls.OBC.CDL.Reals.Add] Add up inputs')
    booToRea: SubBlock = subblock_field(description='[external type: Buildings.Controls.OBC.CDL.Conversions.BooleanToReal] Convert boolean true to real 0')
    cloDam: SubBlock = subblock_field(description='[external type: Buildings.Controls.OBC.CDL.Conversions.BooleanToReal] Full closed damper position')
    conInt3: SubBlock = subblock_field(description='[external type: Buildings.Controls.OBC.CDL.Integers.Sources.Constant] Constant 1')
    conInt4: SubBlock = subblock_field(description='[external type: Buildings.Controls.OBC.CDL.Integers.Sources.Constant] Constant 2')
    intEqu3: SubBlock = subblock_field(description='[external type: Buildings.Controls.OBC.CDL.Integers.Equal] Check if forcing damper to full close')
    intEqu4: SubBlock = subblock_field(description='[external type: Buildings.Controls.OBC.CDL.Integers.Equal] Check if forcing damper to full open')
    opeDam: SubBlock = subblock_field(description='[external type: Buildings.Controls.OBC.CDL.Conversions.BooleanToReal] Full open damper position')
    or2: SubBlock = subblock_field(description='[external type: Buildings.Controls.OBC.CDL.Logical.Or] Check if the damper setpoint position should be overrided')
    pro: SubBlock = subblock_field(description='[external type: Buildings.Controls.OBC.CDL.Reals.Multiply] Valve position setpoint after considering override')
    swi1: SubBlock = subblock_field(description='[external type: Buildings.Controls.OBC.CDL.Reals.Switch] Damper setpoint position after considering override')
