"""AUTO-GENERATED by semantic_objects.ingest - DO NOT EDIT.

Source ontology: /Users/lazlopaul/Desktop/223p/experiments/semantic_objects/.claude/worktrees/cxf-ingestion/src/semantic_objects/ontologies/cxf/Buildings/Controls/OBC/ASHRAE/G36
Source file count SHA256: 381dac3f5fd40eceed32194ddebbd66207c6b6dede645138bc98ffa4913510cc

Regenerate with: python -m semantic_objects.ingest.cli --ontology cxf
Hand customizations belong in the sibling non-generated module, which imports
from this one - never edit this file directly, changes will be overwritten.
"""

from semantic_objects.core import semantic_object
from semantic_objects.cxf.core import Block
from semantic_objects.cxf.core import BooleanInputPort
from semantic_objects.cxf.core import BooleanOutputPort
from semantic_objects.cxf.core import RealInputPort
from semantic_objects.cxf.core import RealOutputPort
from semantic_objects.cxf.core import RealParameter
from semantic_objects.cxf.core import SubBlock
from semantic_objects.cxf.fields import boolean_input_field, boolean_output_field, real_input_field, real_output_field, real_parameter_field, subblock_field
from semantic_objects.qudt import quantitykinds
from semantic_objects.qudt import units

__all__ = ['ReliefFan']


@semantic_object
class ReliefFan(Block):
    _name = 'Buildings.Controls.OBC.ASHRAE.G36.AHUs.MultiZone.VAV.SetPoints.ReliefFan'
    comment = 'info=<html>\n<p>\nSequence for controling relief fan that is part of AHU. It is developed based on\nSection 5.16.9 of ASHRAE Guideline 36, May 2020, with the modification to accommodate\nthe single relief fan control.\n</p>\n<ol>\n<li>\nThe relief fan shall be enabled when the AHU supply fan is proven ON\n(<code>u1SupFan=true</code>), and shall be disabled otherwise.\n</li>\n<li>\nBuilding static pressure (<code>dpBui</code>) shall be time averaged with a sliding\n5-minute window and 15 second sampling rate (to dampen fluctuations). The average\nvalue shall be that displayed and used for control.\n</li>\n<li>\nA P-only control loop maintains the building pressure at a set point (<code>dpBuiSet</code>)\nof 12 Pa (0.05 in. of water) with an output ranging from 0% to 100%. The loop is disabled\nand output set to zero when the relief fan is disabled.\n</li>\n<li>\nFan speed shall be equal to the PID signal but no less than the minimum speed.\n<ol type=\\a\\>\n<li>\nWhen relief system is enabled, and the control loop\noutput is above 5%, open the motorized dampers to the relief fans;\nclose the dampers when the loop output drops to 0% for 5 minutes.\n</li>\n<li>\nWhen the control loop output is above minimum speed (<code>relFanSpe_min</code>) plus 15%\nby 7 minutes, start the relief fan.\n</li>\n<li>\nWhen the control loop output is below minimum speed (<code>relFanSpe_min</code>)\nby 5 minutes, shut off the relief fan.\n</li>\n</ol>\n</li>\n</ol>\n</html>,revisions=<html>\n<ul>\n<li>\nMarch 5, 2024, by Michael Wetter:<br/>\nCorrected wrong use of <code>displayUnit</code>.\n</li>\n<li>\nSeptember 18, 2023, by Jianjun Hu:<br/>\nChanged damper position output from the real to boolean.<br/>\nThis is for\n<a href=\\https://github.com/lbl-srg/modelica-buildings/issues/3526\\>issue 3526</a>.\n</li>\n<li>\nSeptember 20, 2022, by Jianjun Hu:<br/>\nFirst implementation.\n</li>\n</ul>\n</html>'
    dpBui: RealInputPort = real_input_field(qk=quantitykinds.Pressure, unit=units.PA, description='Building static pressure difference, relative to ambient (positive if pressurized)')
    u1SupFan: BooleanInputPort = boolean_input_field(description='AHU supply fan proven on status')
    y1RelDam: BooleanOutputPort = boolean_output_field(description='True: 2-position relief damper commanded open')
    y1RelFan: BooleanOutputPort = boolean_output_field(description='Relief fan commanded on')
    yDpBui: RealOutputPort = real_output_field(qk=quantitykinds.Pressure, unit=units.PA, description='Building static pressure difference, relative to ambient (positive if pressurized)')
    yRelFan: RealOutputPort = real_output_field(unit=units.UNITLESS, description='Relief fan commanded speed')
    dpBuiSet: RealParameter = real_parameter_field(default=12, qk=quantitykinds.Pressure, unit=units.PA, description='Building static pressure difference relative to ambient (positive to pressurize the building)')
    hys: RealParameter = real_parameter_field(default=0.005, description='Hysteresis for checking the controller output value')
    k: RealParameter = real_parameter_field(default=1, unit=units.UNITLESS, description='Gain, normalized using dpBuiSet')
    relFanSpe_min: RealParameter = real_parameter_field(default=0.1, description='Relief fan minimum speed')
    and2: SubBlock = subblock_field(description='[external type: Buildings.Controls.OBC.CDL.Logical.And] Check if the controller output is greater than threshold and the relief system has been enabled')
    booToRea2: SubBlock = subblock_field(description='[external type: Buildings.Controls.OBC.CDL.Conversions.BooleanToReal] Convert boolean to real')
    conOne: SubBlock = subblock_field(description='[external type: Buildings.Controls.OBC.CDL.Reals.Sources.Constant] Constant one')
    conP: SubBlock = subblock_field(description='[external type: Buildings.Controls.OBC.CDL.Reals.PID] Building static pressure controller')
    div1: SubBlock = subblock_field(description='[external type: Buildings.Controls.OBC.CDL.Reals.Divide] Normalized the control error')
    dowTim: SubBlock = subblock_field(description='[external type: Buildings.Controls.OBC.CDL.Logical.Timer] Check if the controller output has been less than threshold for sufficient long time')
    dpBuiSetPoi: SubBlock = subblock_field(description='[external type: Buildings.Controls.OBC.CDL.Reals.Sources.Constant] Building pressure setpoint')
    greThr: SubBlock = subblock_field(description='[external type: Buildings.Controls.OBC.CDL.Reals.GreaterThreshold] Check if the controller output is greater than threshold')
    greThr2: SubBlock = subblock_field(description='[external type: Buildings.Controls.OBC.CDL.Reals.GreaterThreshold] Check if the controller output is greater than minimum speed plus threshold')
    lat: SubBlock = subblock_field(description='[external type: Buildings.Controls.OBC.CDL.Logical.Latch] Enable damper')
    lat1: SubBlock = subblock_field(description='[external type: Buildings.Controls.OBC.CDL.Logical.Latch] Stage down lag fan')
    lesThr: SubBlock = subblock_field(description='[external type: Buildings.Controls.OBC.CDL.Reals.LessThreshold] Check if the controller output is near zero')
    lesThr3: SubBlock = subblock_field(description='[external type: Buildings.Controls.OBC.CDL.Reals.LessThreshold] Check if the controller output is less than minimum speed')
    movMea: SubBlock = subblock_field(description='[external type: Buildings.Controls.OBC.CDL.Reals.MovingAverage] Average building static pressure measurement')
    pro1: SubBlock = subblock_field(description='[external type: Buildings.Controls.OBC.CDL.Reals.Multiply] Relief fan speed')
    relDam: SubBlock = subblock_field(description='[external type: Buildings.Controls.OBC.CDL.Logical.Or] Open relief damper')
    relFan: SubBlock = subblock_field(description='[external type: Buildings.Controls.OBC.CDL.Logical.And] Turn on relief fan')
    tim: SubBlock = subblock_field(description='[external type: Buildings.Controls.OBC.CDL.Logical.Timer] Check if the controller output has been near zero for threshold time')
    upTim: SubBlock = subblock_field(description='[external type: Buildings.Controls.OBC.CDL.Logical.Timer] Check if the controller output has been greater than threshold for sufficient long time')
