"""AUTO-GENERATED by semantic_objects.ingest - DO NOT EDIT.

Source ontology: /Users/lazlopaul/Desktop/223p/experiments/semantic_objects/.claude/worktrees/cxf-ingestion/src/semantic_objects/ontologies/cxf/Buildings/Controls/OBC/ASHRAE/G36
Source file count SHA256: 381dac3f5fd40eceed32194ddebbd66207c6b6dede645138bc98ffa4913510cc

Regenerate with: python -m semantic_objects.ingest.cli --ontology cxf
Hand customizations belong in the sibling non-generated module, which imports
from this one - never edit this file directly, changes will be overwritten.
"""

from semantic_objects.core import semantic_object
from semantic_objects.cxf.core import Block
from semantic_objects.cxf.core import BooleanInputPort
from semantic_objects.cxf.core import BooleanParameter
from semantic_objects.cxf.core import Parameter
from semantic_objects.cxf.core import RealInputPort
from semantic_objects.cxf.core import RealOutputPort
from semantic_objects.cxf.core import RealParameter
from semantic_objects.cxf.core import SubBlock
from semantic_objects.cxf.fields import boolean_input_field, boolean_parameter_field, real_input_field, real_output_field, real_parameter_field, subblock_field, unknown_parameter_field
from semantic_objects.qudt import quantitykinds
from semantic_objects.qudt import units

__all__ = ['SupplySignals']


@semantic_object
class SupplySignals(Block):
    _name = 'Buildings.Controls.OBC.ASHRAE.G36.AHUs.MultiZone.VAV.SetPoints.SupplySignals'
    comment = 'info=<html>\n<p>\nBlock that outputs the supply temperature control loop signal,\nand the coil valve postions for VAV system with multiple zones,\nimplemented according to Section 5.16.2.3 of the ASHRAE Guideline G36, May 2020.\n</p>\n<p>\nThe supply air temperature control loop signal <code>uTSup</code>\nis computed using a PI controller that tracks the supply air temperature\nsetpoint <code>TSupSet</code>.\nIf the fan is off, then <code>uTSup = 0</code>.\n</p>\n<p>\nHeating valve control signal (or modulating electric heating\ncoil if applicable) <code>yHeaCoi</code> and cooling valve control signal <code>yCooCoi</code>\nare sequenced based on the supply air temperature control loop signal <code>uTSup</code>.\nFrom <code>uTSup = uHea_max</code> to <code>uTSup = -1</code>,\n<code>yHeaCoi</code> increases linearly from <i>0</i> to <i>1</i>.\nSimilarly, <code>uTSup = uCoo_min</code> to <code>uTSup = +1</code>,\n<code>yCooCoi</code> increases linearly from <i>0</i> to <i>1</i>.\n</p>\n\n<p align=\\center\\>\n<img alt=\\Image of supply temperature loop\\\nsrc=\\modelica://Buildings/Resources/Images/Controls/OBC/ASHRAE/G36/AHUs/MultiZone/VAV/SetPoints/SupTemLoop.png\\/>\n</p>\n\n<p>\nThe output <code>uTSup</code> can be used in a controller for the economizer.\n</p>\n</html>,revisions=<html>\n<ul>\n<li>\nAugust 1, 2020, by Jianjun Hu:<br/>\nUpdated according to ASHRAE G36 official release.\n</li>\n<li>\nNovember 1, 2017, by Jianjun Hu:<br/>\nFirst implementation.\n</li>\n</ul>\n</html>'
    TAirSup: RealInputPort = real_input_field(qk=quantitykinds.ThermodynamicTemperature, unit=units.K, description='Measured supply air temperature')
    TAirSupSet: RealInputPort = real_input_field(qk=quantitykinds.ThermodynamicTemperature, unit=units.K, description='Supply air temperature setpoint')
    u1SupFan: BooleanInputPort = boolean_input_field(description='Supply fan status')
    uTSup: RealOutputPort = real_output_field(unit=units.UNITLESS, description='Supply temperature control signal')
    yCooCoi: RealOutputPort = real_output_field(unit=units.UNITLESS, description='Cooling coil commanded position')
    yHeaCoi: RealOutputPort = real_output_field(unit=units.UNITLESS, description='Heating coil commanded position')
    controllerType: Parameter = unknown_parameter_field(default='Buildings.Controls.OBC.CDL.Types.SimpleController.PI', description='Type of controller for supply air temperature signal')
    have_cooCoi: BooleanParameter = boolean_parameter_field(default=True, description='True: the AHU has cooling coil. It could be the chilled water coil, or the direct expansion coil')
    have_heaCoi: BooleanParameter = boolean_parameter_field(default=True, description='True: the AHU has heating coil. It could be the hot water coil, or the electric heating coil')
    kTSup: RealParameter = real_parameter_field(default=0.05, unit=units.K, description='Gain of controller for supply air temperature signal')
    TdTSup: RealParameter = real_parameter_field(default=0.1, qk=quantitykinds.Time, unit=units.SEC, description='Time constant of derivative block for supply temperature control signal')
    TiTSup: RealParameter = real_parameter_field(default=600, qk=quantitykinds.Time, unit=units.SEC, description='Time constant of integrator block for supply temperature control signal')
    uCoo_min: RealParameter = real_parameter_field(default=0.25, unit=units.UNITLESS, description='Lower limit of controller signal when cooling coil is off. Require -1 < uHea_max < uCoo_min < 1.')
    uHea_max: RealParameter = real_parameter_field(default=-0.25, unit=units.UNITLESS, description='Upper limit of controller signal when heating coil is off. Require -1 < uHea_max < uCoo_min < 1.')
    conSigCoo: SubBlock = subblock_field(description='[external type: Buildings.Controls.OBC.CDL.Reals.Line] Cooling control signal')
    conSigHea: SubBlock = subblock_field(description='[external type: Buildings.Controls.OBC.CDL.Reals.Line] Heating control signal')
    conTSup: SubBlock = subblock_field(description='[external type: Buildings.Controls.OBC.CDL.Reals.PIDWithReset] Controller for supply air temperature control signal (to be used by heating coil, cooling coil and economizer)')
    negOne: SubBlock = subblock_field(description='[external type: Buildings.Controls.OBC.CDL.Reals.Sources.Constant] Negative unity signal')
    one: SubBlock = subblock_field(description='[external type: Buildings.Controls.OBC.CDL.Reals.Sources.Constant] Unity signal')
    swi: SubBlock = subblock_field(description='[external type: Buildings.Controls.OBC.CDL.Reals.Switch] Switch to select supply temperature control signal based on status of supply fan')
    uCooMinCon: SubBlock = subblock_field(description='[external type: Buildings.Controls.OBC.CDL.Reals.Sources.Constant] Constant signal to map control action')
    uHeaMaxCon: SubBlock = subblock_field(description='[external type: Buildings.Controls.OBC.CDL.Reals.Sources.Constant] Constant signal to map control action')
    zer: SubBlock = subblock_field(description='[external type: Buildings.Controls.OBC.CDL.Reals.Sources.Constant] Zero control signal')
